const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('./helpers/free-agency');
const {createAwardsService,GROUPS}=require('../src/fantasyhq/awards-service');
function setup(t){const f=fixture(t);f.repository.saveLeague('league',{regularSeasonStatus:'COMPLETED',commissionerUserId:'c'});const service=createAwardsService({repository:f.repository,submissions:{records:()=>[],repository:f.repository}}),actor={id:'staff',staffAuthorized:true};return {...f,service,actor};}
test('Staff awards require all five winners, confirmation and permanent IDs',t=>{const f=setup(t),w=Object.fromEntries(GROUPS.REGULAR_SEASON.map((key,i)=>[key,'a-'+i]));assert.throws(()=>f.service.prepare('league',{id:'coach'},'REGULAR_SEASON',w),/Staff/);assert.throws(()=>f.service.prepare('league',f.actor,'REGULAR_SEASON',{MVP:'a-0'}),/every/);const p=f.service.prepare('league',f.actor,'REGULAR_SEASON',w);assert.equal(Object.keys(f.repository.loadAwards('league').seasons).length,0);const record=f.service.confirm('league',f.actor,p.token);assert.equal(record.winners.length,5);assert.equal(record.winners[0].playerId,'a-0');assert.equal(record.winners[0].coachUserId,'coach-a');assert.deepEqual(f.service.confirm('league',f.actor,p.token),record);});
test('award corrections retain history, publication identity and previous seasons',t=>{const f=setup(t),w=Object.fromEntries(GROUPS.REGULAR_SEASON.map(key=>[key,'a-0']));let p=f.service.prepare('league',f.actor,'REGULAR_SEASON',w),r=f.service.confirm('league',f.actor,p.token);f.service.delivery('league','1','REGULAR_SEASON','message',r.revision);assert.throws(()=>f.service.prepare('league',f.actor,'REGULAR_SEASON',w),/correction/);w.MVP='a-1';p=f.service.prepare('league',f.actor,'REGULAR_SEASON',w,'Correct NBA 2K winner');r=f.service.confirm('league',f.actor,p.token);assert.equal(r.history[0].winners[0].playerId,'a-0');assert.equal(r.publication.messageId,'message');f.repository.saveLeague('league',{currentSeasonId:'2'});assert.equal(f.repository.loadAwards('league').seasons['1'].REGULAR_SEASON.winners[0].playerId,'a-1');});
test('player lookup returns team labels for ambiguous names; postseason awards gated',t=>{const f=setup(t),players=f.repository.loadPlayers('league');players[0].name='Jalen Williams';players[15].name='Jaylin Williams';f.repository.savePlayers('league',players);const results=f.service.search('league',f.actor,'Williams');assert.equal(results.length,2);assert.deepEqual(new Set(results.map(p=>p.teamName)),new Set(['Team a','Team b']));assert.throws(()=>f.service.prepare('league',f.actor,'NBA_FINALS',{FINALS_MVP:'a-0'}),/Finish/);});

test('award preview invalidates if owners, players or official source data change',t=>{
 const f=setup(t),w=Object.fromEntries(GROUPS.REGULAR_SEASON.map(key=>[key,'a-0'])),preview=f.service.prepare('league',f.actor,'REGULAR_SEASON',w);
 f.repository.saveOwners('league',[{teamId:'a',userId:'replacement'}]);assert.throws(()=>f.service.confirm('league',f.actor,preview.token),/changed/);assert.equal(Object.keys(f.repository.loadAwards('league').seasons).length,0);
});
test('Discord publishes five award embeds once and edits the same message for corrections',async t=>{
 const f=setup(t),manager=require('../src/fantasyhq/discord-awards').createDiscordAwards({repository:f.repository,submissions:{records:()=>[],repository:f.repository}});
 f.repository.saveSettings('league',{discordChannels:{seasonAwards:'awards'}});let sent=0,edited=0,payload;
 const message={id:'batch',edit:async p=>{edited++;payload=p;}},channel={messages:{fetch:async()=>message},send:async p=>{sent++;payload=p;return message;}},guild={channels:{fetch:async()=>channel}};
 const winners=Object.fromEntries(GROUPS.REGULAR_SEASON.map((key,i)=>[key,'a-'+i])),p=manager.service.prepare('league',f.actor,'REGULAR_SEASON',winners),record=manager.service.confirm('league',f.actor,p.token);
 await Promise.all([manager.publish(guild,'league',record),manager.publish(guild,'league',record)]);await manager.publish(guild,'league',manager.service.confirm('league',f.actor,p.token));
 assert.equal(sent,1);assert.equal(payload.embeds.length,5);assert.ok(payload.embeds.every(e=>e.data.description.includes('<@coach-a>')));
 const correction=manager.service.prepare('league',f.actor,'REGULAR_SEASON',{...winners,MVP:'a-6'},'Correct NBA 2K winner');await manager.publish(guild,'league',manager.service.confirm('league',f.actor,correction.token));
 assert.equal(sent,1);assert.equal(edited,1);assert.equal(payload.embeds.length,5);assert.match(payload.embeds[0].data.description,/a-6/);
});

test('Conference Finals MVPs publish together and Finals MVP publishes separately',async t=>{
 const f=setup(t),stateModule=require('../src/fantasyhq/postseason-state'),teams=['East','West'].flatMap(conference=>Array.from({length:15},(_,i)=>({teamId:conference+i,conference,teamName:conference+i,abbreviation:conference+i}))),seeds=Object.fromEntries(['East','West'].map(c=>[c,teams.filter(t=>t.conference===c).slice(0,10)]));
 f.repository.saveTeams('league',teams);f.repository.saveLeague('league',{currentPhase:'PLAYOFFS'});f.repository.saveRosterMemberships('league',[{playerId:'a-0',teamId:'East0',seasonId:'1',active:true},{playerId:'b-0',teamId:'West0',seasonId:'1',active:true}]);
 const state=stateModule.initializePostseason({leagueId:'league',seasonId:'1',teams,seeds,now:0});state.stage='NBA_FINALS';state.rounds.push({stage:'NBA_FINALS',startedAt:new Date(0).toISOString(),deadlineAt:new Date(96*3600000).toISOString()});
 for(const c of ['East','West']){const series=stateModule.matchup(c+':CF','CONFERENCE_FINALS',c,c+'0',c+'1');series.forfeit={winnerTeamId:c+'0',reason:'Confirmed series forfeit'};state.series.push(series);}
 const final=stateModule.matchup('NBA_FINALS','NBA_FINALS','NBA','East0','West0');final.forfeit={winnerTeamId:'East0',reason:'Confirmed series forfeit'};state.series.push(final);f.repository.commitPostseason({leagueId:'league',playoffs:state,auditEntry:{action:'award-test'}});
 const manager=require('../src/fantasyhq/discord-awards').createDiscordAwards({repository:f.repository,submissions:{records:()=>[],repository:f.repository}}),payloads=[];f.repository.saveSettings('league',{discordChannels:{seasonAwards:'awards'}});const guild={channels:{fetch:async()=>({send:async p=>{payloads.push(p);return {id:'message-'+payloads.length};}})}};
 const cf=manager.service.prepare('league',f.actor,'CONFERENCE_FINALS',{EAST_MVP:'a-0',WEST_MVP:'b-0'});await manager.publish(guild,'league',manager.service.confirm('league',f.actor,cf.token));assert.equal(payloads[0].embeds.length,2);
 const mvp=manager.service.prepare('league',f.actor,'NBA_FINALS',{FINALS_MVP:'a-0'});await manager.publish(guild,'league',manager.service.confirm('league',f.actor,mvp.token));assert.equal(payloads[1].embeds.length,1);assert.match(payloads[1].embeds[0].data.title,/Finals MVP/);assert.equal(f.repository.loadAwards('league').seasons['1'].NBA_FINALS.winners[0].playerId,'a-0');
});
