const test = require('node:test'), assert = require('node:assert/strict'), fs = require('fs'), os = require('os'), path = require('path'), { randomUUID } = require('crypto');
const { createFantasyHQRepository } = require('../src/fantasyhq/repository'), { generateSchedule } = require('../src/fantasyhq/schedule-generator'), { createGameSubmissionService } = require('../src/fantasyhq/game-submissions'), { createGameThreadCleanupService } = require('../src/fantasyhq/game-thread-cleanup');
async function fixture(t) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lb-cleanup-')); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const repository = createFantasyHQRepository({ dataRoot: root });
    const teams = ['East', 'West'].flatMap(conference => Array.from({ length: 15 }, (_, i) => ({ teamId: `${conference}-${i}`, teamName: `${conference} ${i}`, abbreviation: `${conference[0]}${i}`, conference })));
    repository.saveLeague('l', { currentPhase: 'REGULAR_SEASON', currentSeasonId: '1', currentWeek: 2 }); repository.saveTeams('l', teams); repository.saveGuildLeagueBinding('g', { leagueId: 'l', seasonId: '1' }); const schedule = generateSchedule({ leagueId: 'l', seasonId: '1', teams }); schedule.weeks.forEach(w => w.status = w.week === 1 ? 'COMPLETED' : w.week === 2 ? 'ACTIVE' : 'UPCOMING'); repository.saveSchedule(schedule);
    const submissions = createGameSubmissionService({ repository }), channels = new Map(), fail = new Set(), calls = [], fetches = [], bytes = Buffer.from([255, 216, 255, 217]);
    for (const [i, m] of schedule.weeks[0].games.entries()) {
        const threadId = `thread-${i}`, r = submissions.bind({ guildId: 'g', weekNumber: 1, teamQuery: m.team1Id, discordThreadId: threadId, privateThread: true }), sid = randomUUID(), mid = randomUUID();
        const dir = path.join(root, 'game-history', r.game.gameId, 'originals'); fs.mkdirSync(dir, { recursive: true }); fs.writeFileSync(path.join(dir, mid + '.jpg'), bytes);
        await submissions.mutate(r.game.gameId, r => { Object.assign(r.game, { threadCreatedAt: '2026-09-01T00:00:00Z', status: 'FINAL', finalizedAt: '2026-09-03T00:00:00Z', activity: { messages: 3, users: ['coach'] }, result: { submissionId: sid, extractionId: 'corrected', scores: { [m.team1Id]: 120, [m.team2Id]: 110 }, quarters: [30, 30, 30, 30] } }); r.submissions = [{ submissionId: sid, status: 'FINAL', history: ['received', 'approved'] }]; r.media = [{ mediaId: mid, submissionId: sid, storedFile: `originals/${mid}.jpg`, contentType: 'image/jpeg' }]; r.extractions = [{ extractionId: 'original', submissionId: sid, status: 'NEEDS_REVIEW', raw: 'original OCR' }, { extractionId: 'corrected', submissionId: sid, status: 'READY_FOR_REVIEW', issues: [], correctedFrom: 'original' }]; r.playerGameStats = [{ playerId: 'player', teamId: m.team1Id, PTS: 30 }]; r.teamGameStats = [{ teamId: m.team1Id, PTS: 120 }]; r.dnpPlayers = ['bench']; });
        channels.set(threadId, { id: threadId, guildId: 'g', type: 12, delete: async () => { calls.push(threadId); if (fail.has(threadId)) throw Error('Missing permissions'); channels.delete(threadId); } });
    }
    const guild = { id: 'g', channels: { fetch: async id => { fetches.push(id); if (!channels.has(id)) throw Object.assign(Error('Unknown Channel'), { code: 10003 }); return channels.get(id); } } }, actor = { authorized: true, id: 'commish' }, options = { submissions, now: () => Date.parse('2026-10-04T12:00:00Z') }; return { repository, submissions, channels, fail, calls, fetches, bytes, guild, actor, options, service: createGameThreadCleanupService(options) };
}
async function clean(f) { return f.service.cleanup(f.guild, f.actor, (await f.service.prepare(f.guild, f.actor, 1)).token); }
test('all 14 completed threads deleted; every permanent field, original bytes and standings preserved', async t => {
    const f = await fixture(t), before = f.submissions.records(), schedule = f.repository.loadSchedule('l', '1'), standings = require('../src/fantasyhq/standings-service').createStandingsService({ submissions: f.submissions }), table = standings.getStandings('l', '1').conferences;
    const p = await f.service.prepare(f.guild, f.actor, 1); assert.equal(p.found, 14); assert.equal(f.calls.length, 0); const r = await f.service.cleanup(f.guild, f.actor, p.token); assert.equal(r.deleted, 14); assert.equal(r.failed, 0); assert.equal(f.calls.length, 14);
    for (const saved of before) { const after = f.submissions.load(saved.game.gameId); assert.equal(after.game.discordThreadCleanedBy, 'commish'); assert.equal(after.game.discordThreadCleanedAt, '2026-10-04T12:00:00.000Z'); assert.equal(after.game.discordThreadCleanupOutcome, 'DELETED'); assert.ok(after.game.discordThreadDeletedAt); for (const key of ['discordThreadCleanedAt', 'discordThreadCleanedBy', 'discordThreadCleanupOutcome', 'discordThreadDeletedAt']) delete after.game[key]; assert.deepEqual(after, saved); assert.deepEqual(f.submissions.readOriginal(saved.game.gameId, saved.media[0].mediaId), f.bytes); }
    assert.deepEqual(standings.getStandings('l', '1').conferences, table); assert.deepEqual(f.repository.loadSchedule('l', '1'), schedule); const audit = f.repository.loadAuditLog('l'); assert.equal(audit.length, 2); assert.deepEqual([audit[1].userId, audit[1].leagueId, audit[1].seasonId, audit[1].week, audit[1].threadsRequested, audit[1].threadsDeleted, audit[1].threadsAlreadyMissing, audit[1].threadsFailed], ['commish', 'l', '1', 1, 14, 14, 0, 0]); assert.ok(audit[1].timestamp);
});
test('Any scheduled week is selectable; unauthorized coaches and absent confirmation blocked', async t => { const f = await fixture(t); for (const week of [2, 3]) assert.equal((await f.service.prepare(f.guild, f.actor, week)).week, week); await assert.rejects(f.service.prepare(f.guild, f.actor, 999), /unavailable/); await assert.rejects(f.service.prepare(f.guild, { id: 'coach' }, 1), /authorization/); assert.throws(() => f.service.cleanup(f.guild, { id: 'coach' }, 'x'), /authorization/); await assert.rejects(f.service.cleanup(f.guild, f.actor, 'x'), /invalid/); assert.equal(f.calls.length, 0); });
test('confirmation is bound to actor, cancellable and expires', async t => { const f = await fixture(t), p = await f.service.prepare(f.guild, f.actor, 1); await assert.rejects(f.service.cleanup(f.guild, { authorized: true, id: 'other' }, p.token), /invalid/); const later = createGameThreadCleanupService({ ...f.options, now: () => f.options.now() + 360001 }); await assert.rejects(later.cleanup(f.guild, f.actor, p.token), /expired/); f.service.cancel(p.token, f.actor); await assert.rejects(f.service.cleanup(f.guild, f.actor, p.token), /invalid/); assert.equal(f.calls.length, 0); });
test('Active week cleanup deletes unfinished games without changing their status', async t => { const f = await fixture(t), p = await f.service.prepare(f.guild, f.actor, 1), s = f.repository.loadSchedule('l', '1'); s.weeks[0].status = 'ACTIVE'; f.repository.saveSchedule(s); const game = f.submissions.records()[0].game; await f.submissions.mutate(game.gameId, r => { r.game.status = 'SCHEDULED'; }); assert.equal((await f.service.cleanup(f.guild, f.actor, p.token)).deleted, 14); assert.equal(f.submissions.load(game.gameId).game.status, 'SCHEDULED'); assert.equal(f.repository.loadSchedule('l', '1').weeks[0].status, 'ACTIVE'); });
test('double confirmation and subsequent cleanup are idempotent, including restart replay', async t => { const f = await fixture(t), p = await f.service.prepare(f.guild, f.actor, 1); await Promise.all([f.service.cleanup(f.guild, f.actor, p.token), f.service.cleanup(f.guild, f.actor, p.token)]); assert.equal(f.calls.length, 14); assert.equal((await createGameThreadCleanupService(f.options).cleanup(f.guild, f.actor, p.token)).replayed, true); const fetchCount = f.fetches.length, next = await f.service.prepare(f.guild, f.actor, 1); assert.equal(next.found, 0); assert.equal(next.already, 14); const r = await f.service.cleanup(f.guild, f.actor, next.token); assert.equal(r.deleted, 0); assert.equal(r.already, 14); assert.equal(f.fetches.length, fetchCount); });
test('missing threads recorded without failure or claiming actual deletion', async t => { const f = await fixture(t); f.channels.delete('thread-0'); const r = await clean(f); assert.equal(r.deleted, 13); assert.equal(r.already, 1); assert.equal(r.failed, 0); const g = f.submissions.records().find(r => r.game.discordThreadId === 'thread-0').game; assert.equal(g.discordThreadCleanupOutcome, 'MISSING'); assert.ok(g.discordThreadCleanedAt); assert.equal(g.discordThreadDeletedAt, undefined); });
test('partial failure keeps successes; retry touches only two remaining threads', async t => { const f = await fixture(t); f.fail.add('thread-0'); f.fail.add('thread-1'); const r = await clean(f); assert.equal(r.deleted, 12); assert.equal(r.failed, 2); f.fail.clear(); f.calls.length = 0; f.fetches.length = 0; const next = await clean(f); assert.equal(next.deleted, 2); assert.equal(next.already, 12); assert.deepEqual(f.calls.sort(), ['thread-0', 'thread-1']); assert.ok(f.fetches.every(id => ['thread-0', 'thread-1'].includes(id))); });
test('public or foreign channels are never deleted', async t => { const f = await fixture(t); f.channels.get('thread-0').type = 11; f.channels.get('thread-1').guildId = 'other'; const r = await clean(f); assert.equal(r.deleted, 12); assert.equal(r.failed, 2); assert.ok(!f.calls.includes('thread-0') && !f.calls.includes('thread-1')); });
test('historical Game review and original image routes work after cleanup', async t => { const f = await fixture(t); await clean(f); const saved = f.submissions.records()[0], { handleBoxScoreReview } = require('../src/fantasyhq/box-score/review-route'); function get(action, api = true) { let status, body; assert.equal(handleBoxScoreReview({ method: 'GET' }, { writeHead: c => status = c, end: b => body = b }, new URL(`http://localhost/${api ? 'api/' : ''}games/${saved.game.gameId}/submissions/${saved.submissions[0].submissionId}/${action}`), { authorized: true, submissions: f.submissions }), true); assert.equal(status, 200); return body; } const data = JSON.parse(get('review')); assert.equal(data.game.discordThreadCleanedBy, 'commish'); assert.deepEqual(data.extractions, saved.extractions); assert.deepEqual(data.playerGameStats, saved.playerGameStats); assert.deepEqual(get('media/' + saved.media[0].mediaId), f.bytes); assert.match(get('review', false).toString(), /html/); assert.match(fs.readFileSync('web/box-score-review.js', 'utf8'), /Cleaned after Week/); });
test('Discord command enforces staff access and requires explicit delete button', async t => { const f = await fixture(t), { handleCleanupCommand, handleCleanupButton } = require('../src/fantasyhq/discord-game-cleanup'); const base = { guildId: 'g', guild: f.guild, user: { id: 'commish' }, options: { getInteger: () => 1 }, memberPermissions: { has: () => false }, member: { roles: [] } }; await assert.rejects(handleCleanupCommand(base, f.service), /Commish/); let preview; await handleCleanupCommand({ ...base, memberPermissions: { has: () => true }, editReply: async p => preview = p }, f.service); assert.equal(f.calls.length, 0); const buttons = preview.components[0].toJSON().components; assert.equal(buttons[0].label, 'Cancel'); assert.equal(buttons[1].label, 'Delete 14 Threads'); await handleCleanupButton({ ...base, memberPermissions: { has: () => true }, customId: buttons[1].custom_id, deferReply: async () => { }, editReply: async () => { } }, f.service); assert.equal(f.calls.length, 14); });
test('existing website auth, week selection and confirmation protect cleanup', async t => { const f = await fixture(t), { requestHandler, setGameThreadRuntime } = require('../src/web'), { Readable } = require('stream'), old = process.env.WEBSITE_ADMIN_KEY; process.env.WEBSITE_ADMIN_KEY = 'cleanup-test'; t.after(() => { setGameThreadRuntime(null); if (old === undefined) delete process.env.WEBSITE_ADMIN_KEY; else process.env.WEBSITE_ADMIN_KEY = old; }); setGameThreadRuntime({ client: { isReady: () => true, guilds: { fetch: async () => f.guild } }, cleanupService: f.service, repository: f.repository }); function request(body, authorized = true) { return new Promise(resolve => { const req = Readable.from(body ? [JSON.stringify(body)] : []); Object.assign(req, { method: body ? 'POST' : 'GET', url: '/api/league/admin/game-cleanup', headers: authorized ? { 'x-leaguebuddy-admin-key': 'cleanup-test' } : {} }); let code; requestHandler(req, { writeHead: c => code = c, end: b => resolve({ code, data: JSON.parse(b) }) }); }); } assert.equal((await request(null, false)).code, 403); assert.ok((await request()).data.weeks.some(w => w.week === 2 && w.status === 'ACTIVE')); assert.equal((await request({ action: 'confirm', operator: 'Test' })).code, 400); assert.equal((await request({ action: 'prepare', week: 999, operator: 'Test' })).code, 400); const p = await request({ action: 'prepare', week: 1, operator: 'Test' }); assert.equal(f.calls.length, 0); const r = await request({ action: 'confirm', token: p.data.token, operator: 'Test' }); assert.equal(r.data.deleted, 14); const audit = f.repository.loadAuditLog('l')[1]; assert.equal(audit.operator, 'Test'); assert.equal(audit.commissionerUserId, 'website-admin'); });
