const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./helpers/free-agency');
const {createLeagueResetService}=require('../src/fantasyhq/league-reset-service');
test('versioned snapshots and resets preserve permanent players, contracts, championship history and bindings',t=>{
  const f=fixture(t),teams=['East','West'].flatMap(conference=>Array.from({length:15},(_,i)=>({teamId:conference+i,teamName:conference+i,abbreviation:conference+i,conference}))),players=[],members=[];
  for(const team of teams)for(let i=0;i<15;i++){const playerId=team.teamId+'-'+i;players.push({playerId,name:playerId,teamId:team.teamId,overall:80,position1:'PG',contract:{test:'stored'}});members.push({playerId,teamId:team.teamId,seasonId:'1',active:true});}
  f.repository.saveTeams('league',teams);f.repository.savePlayers('league',players);f.repository.saveRosterMemberships('league',members);f.repository.saveLeague('league',{commissionerUserId:'c',guildId:'guild'});
  const service=createLeagueResetService({repository:f.repository}),actor={id:'c',authorized:true},staff={id:'staff',staffAuthorized:true};
  const original=service.saveBase('league',staff,'Original imported roster',true);players[0].overall=95;f.repository.savePlayers('league',players);service.saveBase('league',staff,'Corrected player rating');assert.equal(service.snapshots('league').length,2);assert.equal(service.saveBase('league',staff,'Do not replace original',true).digest,original.digest);
  assert.throws(()=>service.prepare('league',staff),/commissioner/);
  f.repository.commitPostseason({leagueId:'league',playoffs:require('../src/fantasyhq/postseason-state').initializePostseason({leagueId:'league',seasonId:'1',teams,seeds:Object.fromEntries(['East','West'].map(c=>[c,teams.filter(t=>t.conference===c).slice(0,10)]))}),championships:{version:1,seasons:{'1':{teamId:'East0',coachUserId:'historical-coach'}}},auditEntry:{action:'history-fixture'}});
  const p=service.prepare('league',actor),reset=service.confirm('league',actor,p.token);assert.equal(reset.league.currentPhase,'PRESEASON');assert.equal(f.repository.loadPlayers('league')[0].overall,95);assert.equal(f.repository.loadPlayers('league')[0].playerId,players[0].playerId);assert.equal(f.repository.loadLeagueContext({guildId:'guild'}).seasonId,reset.seasonId);assert.deepEqual(service.confirm('league',actor,p.token),reset);
  const full=service.prepare('league',actor,{full:true,version:1});service.confirm('league',actor,full.token);assert.equal(f.repository.loadPlayers('league')[0].overall,80);assert.deepEqual(f.repository.loadPlayers('league')[0].contract,{test:'stored'});assert.equal(service.snapshots('league')[0].digest,original.digest);assert.equal(f.repository.loadChampionships('league').seasons['1'].coachUserId,'historical-coach');assert.equal(f.repository.loadPlayoffs('league','1').seasonId,'1');assert.ok(fs.readdirSync(path.join(f.root,'backups')).length>=2);assert.equal(require('../src/fantasyhq/asset-valuation').leagueSeasonStartYear(reset.seasonId),2026);
});
test('reset journal recovers interrupted multi-file changes and guild binding',t=>{const f=fixture(t);const c=f.repository.loadLeague('league'),seasonId='1-reset-00000000-0000-0000-0000-000000000000';fs.writeFileSync(path.join(c.paths.leagueRoot,'reset-transaction.json'),JSON.stringify({leagueId:'league',seasonId,files:[{name:'league.json',value:{...c.league,currentSeasonId:seasonId,currentPhase:'PRESEASON'}}]}));assert.equal(f.repository.loadLeagueContext({guildId:'guild'}).seasonId,seasonId);assert.equal(fs.existsSync(path.join(c.paths.leagueRoot,'reset-transaction.json')),false);});
