const test=require('node:test'),assert=require('node:assert/strict');const {fixture}=require('./helpers/free-agency');const {createNewsService}=require('../src/fantasyhq/news-service');
async function setup(t){const f=fixture(t);let clock=Date.parse('2026-10-08T12:00:00Z');f.repository.saveLeague('league',{currentWeek:1,commissionerUserId:'c'});f.repository.saveSchedule({leagueId:'league',seasonId:'1',weeks:Array.from({length:6},(_,i)=>({week:i+1,weekId:'w'+(i+1),status:'ACTIVE',games:[{team1Id:'a',team2Id:'b'}],byes:['c']}))});const submissions=require('../src/fantasyhq/game-submissions').createGameSubmissionService({repository:f.repository});async function finalize(week=1){const r=submissions.ensureGame({guildId:'guild',weekNumber:week,teamQuery:'a'});await submissions.mutate(r.game.gameId,record=>{record.submissions=[{submissionId:'s',status:'FINAL'}];record.extractions=[{extractionId:'e',submissionId:'s',status:'READY_FOR_REVIEW',issues:[]}];Object.assign(record.game,{status:'FINAL',finalizedAt:new Date(clock).toISOString(),result:{submissionId:'s',extractionId:'e',scores:{a:110,b:100}}});record.playerGameStats=['a','b'].map(teamId=>({playerId:teamId+'-0',teamId,gameId:record.game.gameId,MIN:35,PTS:40,REB:13,AST:11,STL:4,BLK:2,TO:2,FGM:15,FGA:20,'3PM':4,'3PA':8,FTM:6,FTA:6,OR:3,FLS:2}));});return r.game.gameId;}
 const service=createNewsService({repository:f.repository,submissions,now:()=>clock});return {...f,submissions,service,actor:{id:'c',authorized:true},finalize,advance:h=>clock+=h*3600000};}
test('600 distinct performance scenarios use only measured box-score metrics and qualification',()=>{const {SCENARIOS,matchScenarios}=require('../src/fantasyhq/news-scenarios');assert.equal(SCENARIOS.length,600);assert.equal(new Set(SCENARIOS.map(s=>s.id)).size,600);const log={PTS:40,REB:13,AST:11,STL:4,BLK:2,TO:2,FG:'15-20','3PT':'4-8',FT:'6-6',score:'110-100',result:'W'};assert.ok(matchScenarios(log).some(s=>s.context==='WIN'));assert.ok(!matchScenarios({...log,FG:'4-5'}).some(s=>s.metric==='FG_PERCENT'));assert.ok(!matchScenarios(log).some(s=>s.context==='SEASON_BEST'));});
test('only verified games create drafts; staff approval and spacing control publication with deterministic dedupe',async t=>{
 const f=await setup(t);assert.equal(f.service.detect('league').articles.length,0);await f.finalize();const drafts=f.service.staffList('league',f.actor);assert.equal(drafts.length,2);assert.equal(f.service.list('league').length,0);assert.throws(()=>f.service.review('league',{id:'coach-a'},{id:drafts[0].id,action:'approve'}),/Staff/);for(const a of drafts)f.service.review('league',f.actor,{id:a.id,action:'approve'});assert.equal(f.service.publishDue('league').length,1);assert.equal(f.service.publishDue('league').length,1);f.advance(3);assert.equal(f.service.publishDue('league').length,2);assert.equal(f.service.detect('league').articles.length,2);assert.equal(f.service.list('league',{teamId:'a'}).length,1);assert.equal(f.service.list('league',{category:'Missing'}).length,0);assert.ok(f.service.list('league',{q:'a-0'}).length);const reset=createNewsService({repository:f.repository,submissions:f.submissions});assert.equal(reset.list('league').length,2);
});
test('source corrections require staff review, preserve publication dates and complete revision history',async t=>{
 const f=await setup(t),gameId=await f.finalize(),draft=f.service.staffList('league',f.actor).find(a=>a.playerIds[0]==='a-0');f.service.review('league',f.actor,{id:draft.id,action:'approve'});f.service.publishDue('league');const before=f.service.list('league')[0];await f.submissions.mutate(gameId,r=>{r.playerGameStats[0].REB=20;});const review=f.service.staffList('league',f.actor).find(a=>a.id===draft.id);assert.equal(review.revalidationRequired,true);assert.equal(review.article,before.article);assert.match(review.correctionNotice,/changed/);f.advance(1);const corrected=f.service.review('league',f.actor,{id:draft.id,action:'correct',reason:'Rebound total corrected against the verified box score.'});assert.equal(corrected.publishedAt,before.publishedAt);assert.match(corrected.article,/20 rebounds/);assert.ok(corrected.revisions.some(r=>r.article===before.article));assert.equal(corrected.revalidationRequired,false);assert.throws(()=>f.service.review('league',f.actor,{id:draft.id,action:'reject',reason:'Mistake'}),/Correct/);
});
test('routine publication caps at four daily stories while explicitly approved breaking reports can publish',async t=>{
 const f=await setup(t);for(let w=1;w<=3;w++)await f.finalize(w);for(const story of f.service.staffList('league',f.actor))f.service.review('league',f.actor,{id:story.id,action:'approve'});for(let i=0;i<4;i++){f.service.publishDue('league');f.advance(3);}assert.equal(f.service.list('league').length,4);f.service.publishDue('league');assert.equal(f.service.list('league').length,4);const next=f.service.staffList('league',f.actor).find(a=>a.status==='APPROVED');f.service.review('league',f.actor,{id:next.id,action:'approve',breaking:true});f.service.publishDue('league');assert.equal(f.service.list('league').length,5);
});
test('copied live news remains separate from isolated simulation drafts',async t=>{const f=await setup(t);await f.finalize();f.service.detect('league');f.repository.saveSettings('league',{simulationId:'test'});const sim=f.service.detect('league');assert.equal(sim.articles.length,4);assert.equal(new Set(sim.articles.map(a=>a.id)).size,4);assert.equal(f.service.staffList('league',f.actor).length,2);assert.equal(f.service.list('league').length,0);});

test('corrected performances stay reviewable below all headline thresholds and membership must match at game time',async t=>{
 const f=await setup(t),gameId=await f.finalize(),draft=f.service.staffList('league',f.actor).find(a=>a.playerIds[0]==='a-0');
 f.service.review('league',f.actor,{id:draft.id,action:'approve'});f.service.publishDue('league');
 await f.submissions.mutate(gameId,r=>{Object.assign(r.playerGameStats[0],{PTS:2,REB:1,AST:0,STL:0,BLK:0,TO:1,FGM:1,FGA:10,'3PM':0,'3PA':0,FTM:0,FTA:0});});
 const review=f.service.staffList('league',f.actor).find(a=>a.id===draft.id);assert.ok(review.pendingSource);assert.notEqual(review.sourceUnavailable,true);
 const corrected=f.service.review('league',f.actor,{id:draft.id,action:'correct'});assert.match(corrected.article,/recorded 2 points/);
 const members=f.repository.loadRosterMemberships('league');members.find(m=>m.playerId==='b-0').startedAt='2030-01-01T00:00:00Z';f.repository.saveRosterMemberships('league',members);
 const invalid=f.service.staffList('league',f.actor).find(a=>a.playerIds[0]==='b-0');assert.equal(invalid.sourceUnavailable,true);assert.throws(()=>f.service.review('league',f.actor,{id:invalid.id,action:'approve'}),/source is no longer eligible/);
});
test('audience reactions affect engagement only and combined public filters remain exact',async t=>{
 const f=await setup(t);await f.finalize();const drafts=f.service.staffList('league',f.actor);for(const draft of drafts)f.service.review('league',f.actor,{id:draft.id,action:'approve'});f.service.publishDue('league');f.advance(3);f.service.publishDue('league');
 const article=f.service.list('league',{teamId:'a',playerId:'a-0',seasonId:'1',week:1,phase:'REGULAR_SEASON'})[0];assert.ok(article);assert.equal(f.service.list('league',{teamId:'a',playerId:'b-0'}).length,0);
 const updated=f.service.reactions('league',article.id,{'🔥':4,invalid:-2,fraction:1.5});assert.deepEqual(updated.reactions,{'🔥':4});assert.equal(updated.newsworthiness,article.newsworthiness);assert.equal(updated.publishedAt,article.publishedAt);
});
test('News drafts completed verified transactions while keeping pending trades and unsigned offers private',async t=>{
 const f=await setup(t),at='2026-10-08T12:00:00Z',transfers=[{assetType:'PLAYER',assetId:'a-0',playerName:'a-0',fromTeamId:'a',toTeamId:'b'}];
 f.repository.saveTrades('league',[{tradeId:'trade',seasonId:'1',status:'PENDING_PROOF_REVIEW',currentVersion:{transfers,proof:{staffDecision:null},processing:null}}]);
 assert.equal(f.service.detect('league').articles.length,0);
 const trade=f.repository.loadTrades('league')[0];Object.assign(trade,{status:'COMPLETED',completedAt:at,processingId:'processed'});trade.currentVersion.proof.staffDecision={decision:'APPROVED'};trade.currentVersion.processing={processedAt:at};f.repository.saveTrades('league',[trade]);
 const article=f.service.staffList('league',f.actor)[0];assert.equal(article.category,'Trades');assert.match(article.article,/a-0 moves from Team a to Team b/);assert.equal(f.service.list('league').length,0);
 f.service.review('league',f.actor,{id:article.id,action:'approve'});f.service.publishDue('league');assert.equal(f.service.list('league')[0].category,'Trades');assert.equal(f.service.detect('league').articles.length,1);
 const fa=f.repository.loadFreeAgencyState('league');fa.windows=[{id:'window',seasonId:'1',status:'PENDING',winnerOfferId:'offer',resolvedAt:at}];fa.offers=[{id:'offer',playerId:'fa-0',teamId:'a',status:'APPROVED',contract:f.repository.loadPlayers('league')[0].contract}];f.repository.saveFreeAgencyState('league',fa);
 assert.equal(f.service.detect('league').articles.length,1);fa.windows[0].status='COMPLETED';fa.offers[0].status='WON';f.repository.saveFreeAgencyState('league',fa);
 const signing=f.service.staffList('league',f.actor).find(a=>a.category==='Free agency');assert.ok(signing);assert.match(signing.article,/\$10.00 million/);assert.equal(signing.status,'DRAFT');
});
