const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');
test('News search archives, full articles and stream game pages work without exposing staff controls',async t=>{
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage(),errors=[],queries=[];page.on('pageerror',e=>errors.push(e.message));
 const story={id:'n',seasonId:'1',week:1,phase:'REGULAR_SEASON',category:'Player performance',storyline:'Performance',headline:'Player One lights up the league',article:'Player One scored 40 points. The result was verified. His team won the game. Four steals added defense. The box score tells the story.',publishedAt:'2026-10-08T12:00:00Z',players:[{playerId:'p',name:'Player One'}],teams:[{teamId:'a',teamName:'Team One'}],statistics:{PTS:40,REB:10,AST:8,STL:4,BLK:1,FG:'15-20','3PT':'4-8',FT:'6-6'}};
 const stream={gameId:'g',seasonId:'1',week:1,status:'FINAL',team1Id:'a',team2Id:'b',team1Name:'Team One',team2Name:'Team Two',url:'https://example.com/live',marketLocked:true,result:{scores:{a:110,b:100}},preview:{teams:[{teamName:'Team One',wins:1,losses:0},{teamName:'Team Two',wins:0,losses:1}],playersToWatch:[],breakdown:'Published records and verified roster strength.',prediction:{teamName:'Team One',reason:'Independent model.'}}};
 await page.route('http://news.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('web/index.html','utf8').replace('<script src="/app.js" defer></script>','')});if(url.pathname==='/api/league/news'){queries.push(url.searchParams.toString());return route.fulfill({json:url.searchParams.has('id')?{article:story,related:[]}:{articles:[story],featured:[story],trending:[story],seasons:['1'],categories:[story.category],storylines:['Performance'],teams:story.teams}});}if(url.pathname==='/api/league/streams')return route.fulfill({json:{streams:[stream]}});return route.fulfill({status:404,json:{}});});
 await page.goto('http://news.test/#news');await page.addScriptTag({content:fs.readFileSync('web/app.js','utf8').replace(/^initialize\(\);$/m,'').replace(/^refreshStandings\(\);$/m,'').replace(/^setInterval\(.*$/gm,'')});await page.locator('#news-headlines article').waitFor();assert.equal(await page.locator('#news-featured .news-hero').count(),1);
 await page.locator('#news .filter-panel > summary').click();
 await page.locator('#news-team').selectOption('a');await page.locator('#news-storyline').selectOption('Performance');await page.locator('#news-search').fill('Player One');await page.waitForFunction(()=>document.querySelector('#news-search').value==='Player One');await page.waitForTimeout(450);assert.ok(queries.some(q=>q.includes('teamId=a')&&q.includes('storyline=Performance')&&q.includes('q=Player')));
 await page.locator('#news-headlines [data-news-article]').click();await page.locator('#news-article').waitFor();assert.match(await page.locator('#news-article').textContent(),/40 PTS · 10 REB/);assert.equal((await page.locator('#news-article').textContent()).match(/Player One scored 40 points/g).length,1);
 await page.evaluate(()=>location.hash='#streams');await page.locator('[data-stream-game="g"]').waitFor();await page.locator('[data-stream-game="g"]').click();await page.waitForFunction(()=>document.querySelector('#streams-game-detail').textContent.includes('Game completed'));assert.match(page.url(),/gameId=g/);assert.match(await page.locator('#streams-game-detail').textContent(),/Final: Team One 110 · Team Two 100/);assert.equal(await page.locator('#streams-game-detail a[target="_blank"]').getAttribute('href'),'https://example.com/live');assert.deepEqual(errors,[]);
});
