const test=require('node:test'),assert=require('node:assert/strict');const {fixture}=require('./helpers/free-agency');const {STEPS}=require('../src/fantasyhq/offseason-state');const {createOffseasonFreeAgencyService}=require('../src/fantasyhq/offseason-free-agency');
function setup(t,options={}){const f=fixture(t,options);let clock=Date.parse('2026-10-08');f.repository.saveLeague('league',{currentPhase:'FREE_AGENCY',commissionerUserId:'c'});const p=f.repository.loadPlayers('league');p[0].contract.seasons=p[0].contract.seasons.slice(0,1);p.find(p=>p.playerId==='fa-0').overall=95;f.repository.savePlayers('league',p);f.repository.commitLeagueFiles({leagueId:'league',files:[{name:'offseason.json',value:{version:1,seasons:{'1':{seasonId:'1',step:'FREE_AGENCY',revision:1,completedSteps:STEPS.slice(0,6),history:[],receipts:{}}}}}]});const service=createOffseasonFreeAgencyService({repository:f.repository,now:()=>clock,recognize:async()=>"NBA 2K Transaction Report Signing",backup:()=>{}}),staff={id:'c',authorized:true},coach={id:'coach-a'};return {...f,service,staff,coach,advance:()=>clock+=24*3600000,time:()=>clock};}
const details={salary:10000000,years:'3',option:'None',structure:'Flat'};
test('exclusive re-signing restricts the prior team, pauses and extends, and does not spend open-stage signings',t=>{
 const f=setup(t),s=f.service;s.stageAction('league',f.staff,{action:'open'});assert.throws(()=>s.offer('league',{id:'coach-b'},{teamId:'b',playerId:'a-0',priority:1,details}),/eligible/);s.stageAction('league',f.staff,{action:'pause'});assert.throws(()=>s.offer('league',f.coach,{teamId:'a',playerId:'a-0',priority:1,details}),/closed/);s.stageAction('league',f.staff,{action:'extend',hours:6});s.stageAction('league',f.staff,{action:'resume'});const o=s.offer('league',f.coach,{teamId:'a',playerId:'a-0',priority:1,details});f.advance();assert.throws(()=>s.stageAction('league',f.staff,{action:'close'}),/deadline/);s.stageAction('league',f.staff,{action:'extend',hours:1});f.advance();s.stageAction('league',f.staff,{action:'close'});
 const review=s.prepareApproval('league',f.staff,[o.id]);s.confirmApproval('league',f.staff,review.token);s.stageAction('league',f.staff,{action:'complete'});s.stageAction('league',f.staff,{action:'open'});const status=s.inspect('league',f.coach,{teamId:'a'});assert.equal(status.limits.openSignings,0);assert.equal(status.stage.name,'STAGE_1');assert.equal(f.repository.loadPlayers('league')[0].contract.seasons[0].season,'2027-28');
});
test('stage eligibility, private offers, priorities, Staff confirmation and changed ownership protect signings',t=>{
 const f=setup(t),s=f.service;s.stageAction('league',f.staff,{action:'open'});f.advance();s.stageAction('league',f.staff,{action:'close'});s.stageAction('league',f.staff,{action:'complete'});s.stageAction('league',f.staff,{action:'open'});assert.equal(f.repository.loadPlayers('league')[0].teamId,null);assert.throws(()=>s.offer('league',f.coach,{teamId:'a',playerId:'fa-1',priority:1,details}),/eligible/);
 const low=s.offer('league',f.coach,{teamId:'a',playerId:'fa-0',priority:1,details});const high=s.offer('league',{id:'coach-b'},{teamId:'b',playerId:'fa-0',priority:1,details:{...details,salary:20000000}});assert.equal(s.inspect('league',f.coach,{teamId:'a'}).offers.some(o=>o.id===high.id),false);assert.throws(()=>s.prepareApproval('league',f.staff,[high.id]),/Close/);f.advance();s.stageAction('league',f.staff,{action:'close'});assert.throws(()=>s.prepareApproval('league',f.staff,[low.id]),/highest/);
 const p=s.prepareApproval('league',f.staff,[high.id]);const owners=f.repository.loadOwners('league');owners.find(o=>o.teamId==='b').userId='new';f.repository.saveOwners('league',owners);assert.throws(()=>s.confirmApproval('league',f.staff,p.token),/changed/);owners.find(o=>o.teamId==='b').userId='coach-b';f.repository.saveOwners('league',owners);const again=s.prepareApproval('league',f.staff,[high.id]);const receipt=s.confirmApproval('league',f.staff,again.token);assert.deepEqual(s.confirmApproval('league',f.staff,again.token),receipt);assert.equal(f.repository.loadPlayers('league').find(p=>p.playerId==='fa-0').teamId,'b');assert.equal(s.inspect('league',f.coach,{teamId:'a'}).offers.find(o=>o.id===low.id).status,'LOST');
});
test('offseason scoring uses 35/25/25/15 and does not change regular-season scoring',()=>{const {rankOffseasonOffers,WEIGHTS}=require('../src/fantasyhq/offseason-offer-score');assert.deepEqual(WEIGHTS,{annualSalary:.35,totalValue:.25,length:.25,age:.15});const normalize=require('../src/fantasyhq/offer-score').normalizeOffer;const rows=[1,2].map((n,i)=>({id:String(n),submittedAt:'2026-10-08',contract:normalize({...details,salary:n*10000000},{year:2027}).contract}));const ranked=rankOffseasonOffers(rows,{age:32});assert.equal(ranked[0].id,'2');assert.equal(ranked[0].score,100);assert.deepEqual(rankOffseasonOffers(rows,{age:32}),ranked);});
test('five active offers, unique priorities, three signings per stage and nine across stages survive restart and verified report confirmation',async t=>{
 const f=setup(t,{count:11}),s=f.service,players=f.repository.loadPlayers('league');players.filter(p=>p.playerId.startsWith('fa-')).forEach(p=>{p.overall=95;p.age=25;});f.repository.savePlayers('league',players);s.stageAction('league',f.staff,{action:'open'});f.advance();s.stageAction('league',f.staff,{action:'close'});s.stageAction('league',f.staff,{action:'complete'});
 for(let stage=0;stage<3;stage++){
  s.stageAction('league',f.staff,{action:'open'});const offers=[];for(let n=0;n<3;n++)offers.push(s.offer('league',f.coach,{teamId:'a',playerId:'fa-'+(stage*3+n),priority:n+1,details}));
  if(stage===0){assert.throws(()=>s.offer('league',f.coach,{teamId:'a',playerId:'fa-9',priority:1,details}),/unique priority/);offers.push(s.offer('league',f.coach,{teamId:'a',playerId:'fa-9',priority:4,details}));const fifth=s.offer('league',f.coach,{teamId:'a',playerId:'fa-8',priority:5,details});assert.throws(()=>s.offer('league',f.coach,{teamId:'a',playerId:'fa-7',priority:1,details}),/five active/);s.withdraw('league',f.coach,fifth.id);}
  f.advance();s.stageAction('league',f.staff,{action:'close'});if(stage===0)assert.throws(()=>s.prepareApproval('league',f.staff,offers.map(o=>o.id)),/three signings/);const review=s.prepareApproval('league',f.staff,offers.slice(0,3).map(o=>o.id));s.confirmApproval('league',f.staff,review.token);for(const o of offers.slice(3))s.reject('league',f.staff,{offerId:o.id,reason:'Team signing limit reached'});s.stageAction('league',f.staff,{action:'complete'});
 }
 const state=s.inspect('league',f.staff,{staff:true});assert.equal(state.stages.length,4);assert.equal(state.offers.filter(o=>o.status==='WON').length,9);assert.throws(()=>s.stageAction('league',f.staff,{action:'open'}),/all four|All four/);assert.equal(s.inspect('league',f.coach,{teamId:'a'}).limits.openSignings,9);
 const rows=state.offers.filter(o=>o.status==='WON').map(o=>({offerId:o.id,playerId:o.playerId,teamId:o.teamId,details}));assert.throws(()=>s.prepareVerification('league',f.staff,{rows,reviewedAllImages:true}),/photo/);const sharp=require('sharp');await s.upload('league',f.staff,{filename:'report.jpg',bytes:await sharp({create:{width:50,height:50,channels:3,background:'white'}}).jpeg().toBuffer()});const changed=structuredClone(rows);changed[0].details.salary=1;assert.throws(()=>s.prepareVerification('league',f.staff,{rows:changed,reviewedAllImages:true}),/differs/);const preview=s.prepareVerification('league',f.staff,{rows,reviewedAllImages:true}),receipt=s.confirmVerification('league',f.staff,preview.token);assert.equal(receipt.signings.length,9);assert.deepEqual(s.confirmVerification('league',f.staff,preview.token),receipt);assert.ok(s.inspect('league',f.staff,{staff:true}).receipt.confirmedAt);assert.equal(f.repository.loadOffseason('league').seasons['1'].receipts.FREE_AGENCY.requestId,preview.token);
});
test('coach offer drafts require confirmation and recheck current ownership and stage before placement',t=>{
 const f=setup(t),s=f.service;s.stageAction('league',f.staff,{action:'open'});const draft=s.createDraft('league',f.coach,{teamId:'a',playerId:'a-0'});s.reviewDraft('league',f.coach,draft.id,{details,priority:1});assert.equal(s.inspect('league',f.coach,{teamId:'a'}).offers.length,0);const offer=s.confirmDraft('league',f.coach,draft.id);assert.equal(offer.playerId,'a-0');assert.deepEqual(s.confirmDraft('league',f.coach,draft.id),offer);assert.throws(()=>s.confirmDraft('league',{id:'coach-b'},draft.id),/expired/);
});
test('Discord rechecks coach team roles for offer forms and leaves offers unchanged until confirmation',async t=>{
 const f=setup(t);f.service.stageAction('league',f.staff,{action:'open'});f.repository.saveRoleOwnership('league',{roleIds:{a:'ra',b:'rb',c:'rc'}});const handler=require('../src/fantasyhq/discord-offseason-free-agency').createDiscordOffseasonFreeAgency({repository:f.repository});let modal,reply;const base={guildId:'guild',user:{id:'coach-a'},member:{roles:{cache:new Map([['ra',{}]])}},deferReply:async()=>{},editReply:async p=>reply=p,reply:async p=>reply=p,showModal:async m=>modal=m};
 await handler.handle({...base,customId:'offfa:choose',values:['a-0']});assert.ok(modal);const id=modal.data.custom_id.split(':')[2];await handler.handle({...base,customId:'offfa:details:'+id,fields:{getTextInputValue:key=>({salary:'$10M',years:'3',structure:'Flat',option:'None',priority:'1'})[key]}});assert.equal(f.service.inspect('league',f.coach,{teamId:'a'}).offers.length,0);assert.match(reply.content,/Review your offer/);
 await handler.handle({...base,customId:'offfa:confirm:'+id,member:{roles:{cache:new Map([['rb',{}]])}}});assert.match(reply.content,/must match/);assert.equal(f.service.inspect('league',f.coach,{teamId:'a'}).offers.length,0);await handler.handle({...base,customId:'offfa:confirm:'+id});assert.match(reply.content,/submitted/);assert.equal(f.service.inspect('league',f.coach,{teamId:'a'}).offers.length,1);
});
test('outbid alerts stay private and signing announcements deliver once across repeated sweeps',async t=>{
 const f=setup(t),s=f.service;s.stageAction('league',f.staff,{action:'open'});f.advance();s.stageAction('league',f.staff,{action:'close'});s.stageAction('league',f.staff,{action:'complete'});s.stageAction('league',f.staff,{action:'open'});s.offer('league',f.coach,{teamId:'a',playerId:'fa-0',priority:1,details});const high=s.offer('league',{id:'coach-b'},{teamId:'b',playerId:'fa-0',priority:1,details:{...details,salary:20000000}});f.repository.saveSettings('league',{discordChannels:{announcements:'announcements'}});const dms=[],posts=[],messageMap=new Map();const channel=(id,store)=>({id,messages:{fetch:async()=>messageMap},send:async payload=>{store.push(payload);const m={id:id+store.length,embeds:payload.embeds.map(e=>e.toJSON()),createdTimestamp:f.time()};messageMap.set(m.id,m);return m;}});const publicChannel=channel('announcements',posts),privateChannel=channel('dm',dms),guild={channels:{fetch:async()=>publicChannel},client:{users:{fetch:async id=>{assert.equal(id,'coach-a');return {createDM:async()=>privateChannel};}}}};const make=()=>require('../src/fantasyhq/discord-offseason-market').createDiscordOffseasonMarket({repository:f.repository,now:f.time});
 await make().reconcile(guild,'league');assert.equal(dms.length,1);assert.equal(posts.length,0);assert.doesNotMatch(dms[0].embeds[0].data.description,/20,000,000|coach-b|Team b/);await make().reconcile(guild,'league');assert.equal(dms.length,1);
 f.advance();s.stageAction('league',f.staff,{action:'close'});const preview=s.prepareApproval('league',f.staff,[high.id]);s.confirmApproval('league',f.staff,preview.token);await make().reconcile(guild,'league');assert.equal(posts.length,1);assert.match(posts[0].embeds[0].data.description,/20,000,000/);await make().reconcile(guild,'league');assert.equal(posts.length,1);f.repository.saveSettings('league',{simulationId:'isolated',discordChannels:{announcements:'announcements'}});await make().reconcile(guild,'league');assert.equal(posts.length,1);
});
