const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');
test('options import retains reviewed decisions and requires a separate confirmation; editing invalidates the visible confirmation',async t=>{
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage(),actions=[],errors=[];page.on('pageerror',e=>errors.push(e.message));let confirmed=false;
 const data={step:'OPTIONS',teams:[{teamId:'t',teamName:'Boston Celtics'}],players:[{playerId:'p',name:'Player One',teamId:'t',option:{option:'TEAM'}}],images:[],picks:[],coverage:[],review:null};
 await page.route('http://import.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('web/index.html','utf8').replace('<script src="/app.js" defer></script>','')});if(url.pathname==='/api/league/admin/offseason-import'){
  if(route.request().method()==='GET')return route.fulfill({json:{...data,receipt:confirmed?{confirmedAt:'date'}:null}});const body=route.request().postDataJSON();actions.push(body);if(body.action==='prepare'){if(!body.reviewedAllImages)return route.fulfill({status:400,json:{error:'Review every original photo first.'}});return route.fulfill({json:{token:'token',summary:'One verified option decision'}});}if(body.action==='confirm')confirmed=true;return route.fulfill({json:{confirmed}});
 }return route.fulfill({status:404,json:{}});});
 await page.goto('http://import.test/#admin');await page.addScriptTag({content:fs.readFileSync('web/app.js','utf8').replace(/^initialize\(\);$/m,'').replace(/^refreshStandings\(\);$/m,'').replace(/^setInterval\(.*$/gm,'')});await page.evaluate(()=>{state.adminKey='key';document.querySelector('#admin-operator').value='Commissioner';});
 await page.locator('#offseason-import-kind').selectOption('OPTIONS');await page.locator('#offseason-import-load').click();await page.locator('[data-import-field="decision"]').selectOption('ACCEPTED');await page.locator('#import-prepare').click();await page.getByText('Review every original photo first.').waitFor();assert.equal(confirmed,false);
 await page.locator('#import-reviewed').check();await page.locator('#import-prepare').click();await page.locator('#import-confirm').waitFor();assert.equal(confirmed,false);assert.equal(actions.at(-1).rows[0].decision,'ACCEPTED');
 await page.locator('[data-import-field="decision"]').selectOption('DECLINED');assert.equal(await page.locator('#import-confirm').count(),0);await page.locator('#import-prepare').click();await page.locator('#import-confirm').click();await page.waitForFunction(()=>document.querySelector('#offseason-import-output').textContent.includes('Confirmed'));assert.equal(confirmed,true);assert.equal(actions.filter(a=>a.action==='prepare').at(-1).rows[0].decision,'DECLINED');assert.deepEqual(errors,[]);
});

test('OCR suggestions preserve manual edits, leave conflicting photo values blank and invalidate prior confirmation',async t=>{
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const proposal=(playerId,overall,change)=>({playerId,name:playerId,playerCandidates:[{playerId,name:playerId}],teamId:'t',overall,change,flags:[],confidence:95});
 const data={step:'PROGRESSION',teams:[{teamId:'t',teamName:'Boston Celtics'}],players:[{playerId:'p',name:'Player One',teamId:'t',overall:80},{playerId:'q',name:'Player Two',teamId:'t',overall:80}],images:[{imageId:'photo1',filename:'photo1.heic',status:'READY_FOR_REVIEW',candidates:[],proposals:{rows:[proposal('p',81,1),proposal('q',84,4)],warnings:[]}},{imageId:'photo2',filename:'photo2.heic',status:'READY_FOR_REVIEW',candidates:[],proposals:{rows:[proposal('q',85,4)],warnings:[]}}],picks:[],coverage:[{teamId:'t',teamName:'Boston Celtics',rosterCount:2}],review:null};
 await page.route('http://ocr.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('web/index.html','utf8').replace('<script src="/app.js" defer></script>','')});if(url.pathname==='/api/league/admin/offseason-import')return route.fulfill({json:route.request().method()==='GET'?data:{token:'token',summary:'Reviewed progression'}});return route.fulfill({status:404,json:{}});});
 await page.goto('http://ocr.test/#admin');await page.addScriptTag({content:fs.readFileSync('web/app.js','utf8').replace(/^initialize\(\);$/m,'').replace(/^refreshStandings\(\);$/m,'').replace(/^setInterval\(.*$/gm,'')});await page.evaluate(()=>{state.adminKey='key';document.querySelector('#admin-operator').value='Commissioner';});
 await page.locator('#offseason-import-kind').selectOption('PROGRESSION');await page.locator('#offseason-import-load').click();
 const p=page.locator('[data-import-field="overall"][data-import-row="0"]');await p.fill('90');await page.locator('#import-reviewed').check();await page.locator('#import-prepare').click();await page.locator('#import-confirm').waitFor();
 await page.locator('#import-apply-ocr').click();assert.equal(await p.inputValue(),'90');assert.equal(await page.locator('[data-import-field="change"][data-import-row="0"]').inputValue(),'1');assert.equal(await page.locator('[data-import-field="overall"][data-import-row="1"]').inputValue(),'');assert.equal(await page.locator('#import-reviewed').isChecked(),false);assert.equal(await page.locator('#import-confirm').count(),0);assert.deepEqual(errors,[]);
});
