const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright');
test('postseason page renders official bracket and historical/stat scope selectors on mobile',async t=>{
  const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const seeds={East:Array.from({length:10},(_,i)=>({teamId:'e'+i,teamName:'East '+i})),West:Array.from({length:10},(_,i)=>({teamId:'w'+i,teamName:'West '+i}))};
  const state={version:2,stage:'PLAY_IN',seeds,qualifiedSeeds:{},conflicts:[],rounds:[{stage:'PLAY_IN',deadlineAt:'2026-10-09T00:00:00Z'}],series:[{id:'East:7-8',stage:'PLAY_IN',conference:'East',team1Id:'e6',team2Id:'e7',wins:{e6:1,e7:0},winnerTeamId:'e6',status:'COMPLETE',requiredWins:1}]};
  await page.route('http://postseason.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/'){await route.fulfill({contentType:'text/html',body:fs.readFileSync('web/index.html','utf8').replace('<script src="/app.js" defer></script>','')});return;}if(url.pathname==='/styles.css'){await route.fulfill({contentType:'text/css',body:fs.readFileSync('web/styles.css','utf8')});return;}if(url.pathname==='/api/league/playoffs'){await route.fulfill({json:{playoffs:state,seasonId:url.searchParams.get('season')||'2',seasons:['1','2'],games:[{seriesId:'East:7-8',gameNumber:1,result:{scores:{e6:100,e7:90}}}],testMode:false}});return;}if(url.pathname==='/api/league/stats'){await route.fulfill({json:{players:[{playerId:'p',name:'Scoped Player',GP:1,PPG:url.searchParams.get('scope')==='PLAY_IN'?12:25,RPG:5,APG:5,SPG:1,BPG:1,MPG:30,TOV:1}],warnings:[]}});return;}await route.fulfill({status:404,json:{error:'Not used'}});});
  await page.goto('http://postseason.test/');const app=fs.readFileSync('web/app.js','utf8').replace(/^initialize\(\);$/m,'').replace(/^refreshStandings\(\);$/m,'').replace(/^setInterval\(.*$/gm,'');await page.addScriptTag({content:app});await page.locator('.postseason-matchup').waitFor();assert.match(await page.locator('#playoffs-bracket').textContent(),/East 6/);await page.locator('#playoffs-season').selectOption('1');await page.waitForFunction(()=>document.querySelector('#playoffs-status').textContent.includes('Season 1'));assert.equal(await page.locator('#player-stats-season option').count(),3);await page.locator('#player-stats-scope').selectOption('PLAY_IN');await page.waitForFunction(()=>document.querySelector('#league-stats-body').textContent.includes('Scoped Player'));assert.equal(await page.locator('[data-player-stat-sort]').count()>=0,true);assert.deepEqual(errors,[]);
});
