const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./helpers/free-agency');
const {createSimulationStorage}=require('../src/fantasyhq/simulation-storage');
test('simulation workspaces and checkpoints preserve live bytes and immutable starting state',t=>{const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c',guildId:'guild'});const service=createSimulationStorage({repository:f.repository}),actor={id:'c',authorized:true};const before=fs.readFileSync(f.repository.loadLeague('league').paths.playersFile,'utf8');assert.throws(()=>service.create('league',{id:'staff',authorized:true}),/commissioner/);const sim=service.create('league',actor),players=sim.repository.loadPlayers('league');players[0].overall=99;sim.repository.savePlayers('league',players);assert.equal(fs.readFileSync(f.repository.loadLeague('league').paths.playersFile,'utf8'),before);const cp=service.checkpoint(sim.id,actor,'Changed roster');assert.equal(service.checkpoints(sim.id,actor).length,2);const start=service.checkpoints(sim.id,actor).find(c=>c.name==='Starting state');assert.throws(()=>service.restore(sim.id,actor,start.id),/confirmation/);let restored=service.restore(sim.id,actor,start.id,true);assert.equal(restored.repository.loadPlayers('league')[0].overall,80);restored=service.restore(sim.id,actor,cp.id,true);assert.equal(restored.repository.loadPlayers('league')[0].overall,99);assert.equal(fs.readdirSync(path.join(sim.dir,'safety')).length,2);assert.equal(fs.readFileSync(f.repository.loadLeague('league').paths.playersFile,'utf8'),before);});
test('corrupted checkpoints fail before modifying the current simulation',t=>{const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c'});const service=createSimulationStorage({repository:f.repository}),actor={id:'c',authorized:true},sim=service.create('league',actor),cp=service.checkpoints(sim.id,actor)[0];const file=path.join(sim.dir,'checkpoints',cp.id,'data','leagues','league','players.json'),before=fs.readFileSync(sim.repository.loadLeague('league').paths.playersFile,'utf8');fs.writeFileSync(file,'[]');assert.throws(()=>service.restore(sim.id,actor,cp.id,true),/corrupted/);assert.equal(fs.readFileSync(sim.repository.loadLeague('league').paths.playersFile,'utf8'),before);});

test('interrupted checkpoint restoration completes from its journal with the old workspace backed up',t=>{
 const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c'});const storage=createSimulationStorage({repository:f.repository}),actor={id:'c',authorized:true},sim=storage.create('league',actor),start=storage.checkpoints(sim.id,actor)[0],players=sim.repository.loadPlayers('league');players[0].overall=99;sim.repository.savePlayers('league',players);
 const rename=fs.renameSync;let interrupted=false;fs.renameSync=(from,to)=>{if(!interrupted&&from===path.join(sim.dir,'restore-candidate')){interrupted=true;throw Error('Simulated disk interruption');}return rename(from,to);};
 try{assert.throws(()=>storage.restore(sim.id,actor,start.id,true),/interruption/);}finally{fs.renameSync=rename;}
 assert.equal(storage.load(sim.id,actor).repository.loadPlayers('league')[0].overall,80);assert.equal(fs.existsSync(path.join(sim.dir,'restore.json')),false);const backups=fs.readdirSync(path.join(sim.dir,'safety'));assert.equal(backups.length,1);assert.equal(JSON.parse(fs.readFileSync(path.join(sim.dir,'safety',backups[0],'leagues','league','players.json')))[0].overall,99);
});

test('restart recovers a running simulation even when container PID is reused',t=>{
 const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c'});const storage=createSimulationStorage({repository:f.repository}),actor={id:'c',authorized:true},sim=storage.create('league',actor);
 const file=path.join(sim.workspace,'simulation-runtime.json'),runtime=storage.runtime(sim.id,actor);
 fs.writeFileSync(file,JSON.stringify({...runtime,status:'RUNNING',processId:process.pid,processToken:'previous-container',plan:{weeks:3},pauseRequested:true}));
 const recovered=storage.runtime(sim.id,actor);assert.equal(recovered.status,'PAUSED');assert.match(recovered.errors[0].error,/Previous simulation process stopped/);
 storage.saveRuntime(sim.id,actor,{...recovered,status:'RUNNING'});assert.equal(storage.runtime(sim.id,actor).status,'RUNNING');
});
