const test=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('./helpers/free-agency');
const {createSimulationStorage}=require('../src/fantasyhq/simulation-storage');
test('isolated simulated two/three-team trades enforce roster sizes, five-trade cap and deadline',t=>{
  const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c'});const storage=createSimulationStorage({repository:f.repository}),sim=storage.create('league',{id:'c',authorized:true}),repo=sim.repository,service=require('../src/fantasyhq/trade-service').createTradeService({repository:repo});
  const swap=()=>service.completeSimulatedTrade({leagueId:'league',actorUserId:'TEST MODE',participatingTeams:['a','b'],transfers:[{assetType:'PLAYER',assetId:repo.loadRosterMemberships('league').find(m=>m.teamId==='a'&&m.active!==false).playerId,fromTeamId:'a',toTeamId:'b'},{assetType:'PLAYER',assetId:repo.loadRosterMemberships('league').find(m=>m.teamId==='b'&&m.active!==false).playerId,fromTeamId:'b',toTeamId:'a'}]});
  assert.equal(swap().status,'COMPLETED');
  const current=repo.loadRosterMemberships('league'),triplet=['a','b','c'].map((teamId,i)=>({assetType:'PLAYER',assetId:current.find(m=>m.teamId===teamId&&m.active!==false).playerId,fromTeamId:teamId,toTeamId:['a','b','c'][(i+1)%3]}));assert.equal(service.completeSimulatedTrade({leagueId:'league',actorUserId:'TEST MODE',participatingTeams:['a','b','c'],transfers:triplet}).status,'COMPLETED');
  for(let i=0;i<3;i++)swap();assert.throws(swap,/5\/5|5 trades/);assert.equal(repo.loadTrades('league').filter(t=>t.status==='COMPLETED').length,5);assert.ok(repo.loadTrades('league').every(t=>t.simulationId===sim.id));assert.equal(f.repository.loadTrades('league').length,0);
  repo.saveLeague('league',{currentWeek:10});assert.throws(swap,/Week 9/);
  for(const teamId of ['a','b','c'])assert.equal(repo.loadRosterMemberships('league').filter(m=>m.teamId===teamId&&m.active!==false).length,15);
});
test('simulated signing and conditional waiver preserve fifteen players and freeze in playoffs',t=>{const f=fixture(t);f.repository.saveLeague('league',{commissionerUserId:'c'});const storage=createSimulationStorage({repository:f.repository}),sim=storage.create('league',{id:'c',authorized:true}),service=require('../src/fantasyhq/free-agency-service').createFreeAgencyService({repository:sim.repository});service.simulateReplacement('league',{teamId:'a',playerId:'fa-0',releasePlayerId:'a-0',actorUserId:'TEST MODE'});assert.equal(sim.repository.loadRosterMemberships('league').filter(m=>m.teamId==='a'&&m.active!==false&&!m.endedAt).length,15);assert.equal(sim.repository.loadPlayers('league').find(p=>p.playerId==='fa-0').teamId,'a');assert.equal(f.repository.loadPlayers('league').find(p=>p.playerId==='fa-0').teamId,null);sim.repository.saveLeague('league',{currentPhase:'PLAYOFFS'});assert.throws(()=>service.simulateReplacement('league',{teamId:'a',playerId:'fa-1',releasePlayerId:'a-1',actorUserId:'TEST MODE'}),/frozen/);});
