const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');
test('private sportsbook signs in from fragment, reviews exact odds and clears stale confirmation when wager changes',async t=>{
 const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage(),errors=[],requests=[],token='a'.repeat(64);page.on('pageerror',error=>errors.push(error.message));
 const markets=[{id:'ml-a',gameId:'g',week:1,group:'ml',kind:'MONEYLINE',selection:'a',line:null,odds:-145,status:'OPEN',teamIds:['a','b']},{id:'own',gameId:'own-game',week:1,group:'own',kind:'MONEYLINE',selection:'c',line:null,odds:100,status:'OPEN',teamIds:['c','d']}];let placed=false;
 const profile={balanceCents:30000,wins:0,losses:0,careerProfitCents:0,totalWageredCents:0,bestWinningStreak:0};
 const preview={id:'bet-token',legs:[markets[0]],stakeCents:1000,profitCents:690,potentialReturnCents:1690};
 await page.route('http://book.test/**',async route=>{const url=new URL(route.request().url()),body=route.request().postDataJSON();if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('web/index.html','utf8').replace(/<script src="\/(?:app|sportsbook)\.js" defer><\/script>/g,'')});
  if(url.pathname==='/api/league/coach-session'){requests.push(body);return route.fulfill({json:{coachUserId:'coach-c',teamId:'c'}});}
  if(url.pathname==='/api/league/sportsbook')return route.fulfill({json:{seasonId:'1',week:1,markets,games:[{gameId:'g',team1Id:'a',team2Id:'b',team1Name:'Team A',team2Name:'Team B'},{gameId:'own-game',team1Id:'c',team2Id:'d',team1Name:'My Team',team2Name:'Team D'}],leaderboard:[]}});
  if(url.pathname==='/api/league/sportsbook/mine')return route.fulfill({json:{teamId:'c',coachUserId:'coach-c',profile:{...profile,balanceCents:placed?29000:30000},bets:placed?[{...preview,placedAt:'2026-10-08T12:00:00Z',status:'OPEN',settlements:[]}]:[]}});
  if(url.pathname==='/api/league/sportsbook/bet'){requests.push(body);if(body.action==='confirm')placed=true;return route.fulfill({json:preview});}return route.fulfill({status:404,json:{}});
 });
 await page.goto('http://book.test/#coach-login='+token);await page.addScriptTag({content:fs.readFileSync('web/app.js','utf8').replace(/^initialize\(\);$/m,'').replace(/^refreshStandings\(\);$/m,'').replace(/^setInterval\(.*$/gm,'')});await page.addScriptTag({content:fs.readFileSync('web/sportsbook.js','utf8')});await page.locator('[data-book-market="ml-a"]').waitFor();assert.equal(new URL(page.url()).hash,'#sportsbook');assert.ok(requests.some(r=>r.token===token));assert.equal(await page.locator('[data-book-market="own"]').isDisabled(),true);
 await page.locator('[data-book-market="ml-a"]').click();await page.locator('#sportsbook-preview').click();await page.locator('[data-book-confirm]').waitFor();assert.match(await page.locator('#sportsbook-confirmation').textContent(),/Potential profit \$6.90 · Total return \$16.90/);
 await page.locator('#sportsbook-wager').fill('11');assert.equal(await page.locator('[data-book-confirm]').count(),0);await page.locator('#sportsbook-wager').fill('10');await page.locator('#sportsbook-preview').click();await page.locator('[data-book-confirm]').click();await page.waitForFunction(()=>document.querySelector('#sportsbook-profile').textContent.includes('$290.00'));assert.ok(requests.some(r=>r.action==='confirm'&&r.token==='bet-token'));assert.match(await page.locator('#sportsbook-bets').textContent(),/OPEN/);assert.deepEqual(errors,[]);
});
