const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');const {fixture}=require('./helpers/free-agency');
test('Sportsbook API derives coach identity from the private cookie and current Discord roles, ignoring supplied user/team IDs',async t=>{
 const f=fixture(t),saved={};for(const key of ['FANTASYHQ_DATA_ROOT','GUILD_ID','WEBSITE_URL'])saved[key]=process.env[key];process.env.FANTASYHQ_DATA_ROOT=f.root;process.env.GUILD_ID='guild';process.env.WEBSITE_URL='https://league.test';t.after(()=>{for(const [key,value]of Object.entries(saved)){if(value===undefined)delete process.env[key];else process.env[key]=value;}});
 f.repository.saveLeague('league',{currentWeek:1});f.repository.saveRoleOwnership('league',{roleIds:{a:'ra',b:'rb',c:'rc'}});f.repository.saveSchedule({leagueId:'league',seasonId:'1',weeks:[{week:1,weekId:'w1',status:'ACTIVE',games:[{team1Id:'a',team2Id:'b'}],byes:['c']}]});
 const submissions=require('../src/fantasyhq/game-submissions').createGameSubmissionService({repository:f.repository});submissions.ensureGame({guildId:'guild',weekNumber:1,teamQuery:'a'});
 const member={roles:{cache:new Map([['rc',{}]])}},sessions=require('../src/fantasyhq/coach-web-session').createCoachWebSessions({repository:f.repository});const secret=new URL(sessions.issue('league',{id:'coach-c',member,guildId:'guild'}).url).hash.slice('#coach-login='.length);
 const web=require('../src/web');web.setGameThreadRuntime({repository:f.repository,client:{isReady:()=>true,guilds:{fetch:async()=>({members:{fetch:async options=>{assert.equal(options.user,'coach-c');assert.equal(options.force,true);return member;}}})}}});web.setPlayerUpgradeRuntime({submissions});
 function request(url,{method='GET',body=null,cookie=null,origin='https://league.test'}={}) {return new Promise(resolve=>{const req=Object.assign(require('node:stream').Readable.from(body===null?[]:[Buffer.from(JSON.stringify(body))]),{url,method,headers:{origin,...(cookie?{cookie}:{})}}),headers={};let status;web.requestHandler(req,{setHeader:(key,value)=>headers[key]=value,writeHead:code=>status=code,end:data=>resolve({status,headers,data:JSON.parse(data)})});});}
 assert.match((await request('/api/league/sportsbook/mine')).data.error,/Sign in/);const publicData=await request('/api/league/sportsbook');assert.equal(publicData.status,200);assert.equal('bets'in publicData.data,false);assert.equal('wallets'in publicData.data,false);
 const login=await request('/api/league/coach-session',{method:'POST',body:{token:secret}});assert.equal(login.status,200);const cookie=login.headers['Set-Cookie'].split(';')[0];assert.equal(login.data.coachUserId,'coach-c');
 const mine=await request('/api/league/sportsbook/mine?userId=coach-a',{cookie});assert.equal(mine.data.coachUserId,'coach-c');assert.equal(mine.data.teamId,'c');
 const preview=await request('/api/league/sportsbook/bet',{method:'POST',cookie,body:{action:'preview',marketIds:[publicData.data.markets[0].id],wager:'10',userId:'coach-a',teamId:'a'}});assert.equal(preview.status,200);assert.equal(preview.data.userId,'coach-c');
 const confirm=await request('/api/league/sportsbook/bet',{method:'POST',cookie,body:{action:'confirm',token:preview.data.id,userId:'coach-a'}});assert.equal(confirm.status,200);assert.equal(confirm.data.userId,'coach-c');
 assert.equal((await request('/api/league/sportsbook/mine',{cookie})).data.profile.balanceCents,29000);
 const invalid=await request('/api/league/sportsbook/bet',{method:'POST',cookie,origin:'https://evil.test',body:{action:'confirm',token:preview.data.id}});assert.match(invalid.data.error,/configured league website/);
 assert.equal((await request('/api/league/admin/sportsbook')).status,403);
 member.roles.cache=new Map([['ra',{}]]);assert.match((await request('/api/league/sportsbook/mine',{cookie})).data.error,/assignment must match/);
});
