const test=require('node:test'),assert=require('node:assert/strict');
const {setTeamEmojis,teamEmoji,teamLabel,loadTeamEmojis}=require('../src/shared/team-emojis');
const names='bos bkn nyk phi tor chi cle det ind mil atl cha mia orl wsh gs lac lal phe sac den min okc por uth dal hou mem no san'.split(' ');
function seed(){setTeamEmojis(new Map(names.map((name,i)=>[name,{name,id:String(1556647456723443763n+BigInt(i))}])));}
test('all 30 screenshot names map to NBA teams with readable fallback',()=>{seed();for(const t of require('../web/assets/nba/teams.json')){assert.match(teamEmoji(t.name),/^<:\w+:\d+>$/);assert.equal(teamEmoji(t.slug),teamEmoji(t.abbreviation));assert.ok(teamLabel(t.name).endsWith(t.name));}assert.equal(teamLabel('Duke'),'Duke');setTeamEmojis(new Map());assert.equal(teamLabel('Boston Celtics'),'Boston Celtics');});
test('application emoji loading uses API IDs and tolerates unavailable API',async()=>{let requested=false;await loadTeamEmojis({application:{emojis:{fetch:async()=>{requested=true;return new Map([['bos',{name:'bos',id:'123456789012345678',animated:true}]]);}}}},{log(){},warn(){}});assert.equal(requested,true);assert.equal(teamEmoji('BOS'),'<a:bos:123456789012345678>');let warning;await loadTeamEmojis({application:{emojis:{fetch:async()=>{throw Error('offline');}}}},{warn:s=>warning=s});assert.match(warning,/remain readable/);setTeamEmojis(new Map());});
test('team emojis appear in standings, all schedule pages and game messages within embed limits',()=>{
 seed();const teams=require('../web/assets/nba/teams.json').map((t,i)=>({teamId:t.slug,teamName:t.name,conference:i<15?'East':'West'}));const schedule=require('../src/fantasyhq/schedule-generator').generateSchedule({leagueId:'l',seasonId:'1',teams});
 const {previewPayload}=require('../src/fantasyhq/discord-schedule');for(let i=0;i<15;i++){const p=previewPayload({league:{name:'Test'},teams},{pendingScheduleId:'p',schedule},i);for(const f of p.embeds[0].data.fields){assert.match(f.value,/<:/);assert.ok(f.value.length<=1024);}}
 const {standingsPayload}=require('../src/fantasyhq/discord-standings');const rows=teams.map((t,i)=>({...t,rank:i+1,W:0,L:0,PCT:0,GP:0,PF:0,PA:0,DIFF:0}));for(const e of standingsPayload({conferences:{East:rows.slice(0,15),West:rows.slice(15)},currentWeek:1}).embeds){assert.match(e.data.description,/<:/);assert.ok(e.data.description.length<=4096);}
 const {gamePayload}=require('../src/fantasyhq/discord-game-submissions');assert.match(gamePayload({gameId:'g',weekNumber:1,team1Name:'Boston Celtics',team2Name:'Miami Heat'}).embeds[0].data.description,/<:bos:/);setTeamEmojis(new Map());
});
