const test = require('node:test'), assert = require('node:assert/strict'), fs = require('fs'), os = require('os'), path = require('path');
const { createFantasyHQRepository } = require('../src/fantasyhq/repository'); const { createLeagueService } = require('../src/fantasyhq/league-service'); const { generateSchedule } = require('../src/fantasyhq/schedule-generator'); const { createGameSubmissionService } = require('../src/fantasyhq/game-submissions'); const { createWeekAdvancementService } = require('../src/fantasyhq/week-advancement');
function fixture(t) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lb-advance-')); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const repository = createFantasyHQRepository({ dataRoot: root }); const teams = ['East', 'West'].flatMap(conference => Array.from({ length: 15 }, (_, i) => ({ teamId: `${conference}-${i}`, teamName: `${conference} ${i}`, abbreviation: `${conference[0]}${i}`, conference }))); repository.saveLeague('l', { currentPhase: 'PRESEASON', currentSeasonId: '1', commissionerUserId:'commish' }); repository.saveTeams('l', teams); repository.saveGuildLeagueBinding('g', { leagueId: 'l', seasonId: '1' }); repository.saveSchedule(generateSchedule({ leagueId: 'l', seasonId: '1', teams })); createLeagueService({ repository }).startRegularSeason({ leagueId: 'l', seasonId: '1', validator: () => ({ ready: true }) }); const submissions = createGameSubmissionService({ repository }), calls = []; const threads = { create: async guild => { calls.push(guild.id); return { created: 14, existing: 0, failed: 0 }; } }; const actor = { authorized: true, id: 'commish' }, guild = { id: 'g' }, options = { submissions, threads, now: () => Date.parse('2026-10-03T12:00:00Z') }, service = createWeekAdvancementService(options);
    async function finals(week = 1, number = 14) { const saved = repository.loadSchedule('l', '1').weeks.find(w => w.week === week); for (const match of saved.games.slice(0, number)) { const r = submissions.ensureGame({ guildId: 'g', weekNumber: week, teamQuery: match.team1Id }); await submissions.mutate(r.game.gameId, r => { r.submissions = [{ submissionId: 's', status: 'FINAL' }]; r.extractions = [{ extractionId: 'e', submissionId: 's', status: 'READY_FOR_REVIEW', issues: [] }]; Object.assign(r.game, { status: 'FINAL', finalizedAt: '2026-10-03T00:00:00Z', result: { submissionId: 's', extractionId: 'e', scores: { [match.team1Id]: 120, [match.team2Id]: 110 } } }); }); } }
    return { repository, submissions, service, options, threads, calls, actor, guild, finals };
}
test('normal advancement atomically activates next week, preserves games/standings/byes and invokes existing creator', async t => { const f = fixture(t); await f.finals(); const records = f.submissions.records(), before = f.repository.loadSchedule('l', '1'); const standings = require('../src/fantasyhq/standings-service').createStandingsService({ submissions: f.submissions }).getStandings('l', '1').conferences; const prep = f.service.prepare('g', f.actor); const result = await f.service.advance(f.guild, f.actor, prep.token); assert.equal(result.currentWeek, 2); assert.equal(result.threads.created, 14); assert.equal(f.calls.length, 1); const after = f.repository.loadSchedule('l', '1'); assert.equal(after.weeks[0].status, 'COMPLETED'); assert.equal(after.weeks[1].status, 'ACTIVE'); assert.equal(after.weeks.filter(w => w.status === 'ACTIVE').length, 1); assert.equal(after.weeks[1].deadlineAt, undefined); assert.equal(f.repository.loadLeague('l').league.currentWeek, 2); assert.deepEqual(after.weeks.map(w => [w.games, w.byes]), before.weeks.map(w => [w.games, w.byes])); assert.deepEqual(f.submissions.records(), records); assert.deepEqual(require('../src/fantasyhq/standings-service').createStandingsService({ submissions: f.submissions }).getStandings('l', '1').conferences, standings); });
test('week advance invokes the feed/mock refresh hook after publishing stats', async t => { const f = fixture(t); await f.finals(); let called = 0; const service = createWeekAdvancementService({ ...f.options, onAdvanced: async ({ guild, leagueId, seasonId, result }) => { called += 1; assert.equal(guild.id, 'g'); assert.equal(leagueId, 'l'); assert.equal(seasonId, '1'); assert.equal(result.currentWeek, 2); assert.equal(f.repository.loadSchedule('l', '1').statsPublication.throughWeek, 1); } }); const prep = service.prepare('g', f.actor); await service.advance(f.guild, f.actor, prep.token); assert.equal(called, 1); });
test('unresolved games block normal advance, show links and force requires confirmed commissioner action', async t => { const f = fixture(t); await f.finals(1, 12); const week = f.repository.loadSchedule('l', '1').weeks[0]; f.submissions.bind({ guildId: 'g', weekNumber: 1, teamQuery: week.games[12].team1Id, discordThreadId: 'existing', privateThread: true }); const blocked = f.service.prepare('g', f.actor); assert.equal(blocked.blocked, true); assert.equal(blocked.final, 12); assert.equal(blocked.unresolved.length, 2); assert.match(blocked.unresolved[0].threadUrl, /existing/); assert.throws(() => f.service.prepare('g', { id: 'coach' }, true), /authorization/); await assert.rejects(f.service.advance(f.guild, f.actor, 'no-confirmation'), /invalid/); const before = f.submissions.records(), forced = f.service.prepare('g', f.actor, true); await f.service.advance(f.guild, f.actor, forced.token); assert.deepEqual(f.submissions.records(), before); const audit = f.repository.loadAuditLog('l').find(a => a.action === 'week.advanced'); assert.equal(audit.userId, 'commish'); assert.equal(audit.force, true); assert.equal(audit.unresolved.length, 2); assert.equal(f.repository.loadSchedule('l', '1').weeks[0].unresolvedAtCompletion.length, 2); });
test('double clicks, distinct stale confirmations and replay after restart cannot skip weeks', async t => { const f = fixture(t); await f.finals(); const a = f.service.prepare('g', f.actor), b = f.service.prepare('g', f.actor); await Promise.all([f.service.advance(f.guild, f.actor, a.token), f.service.advance(f.guild, f.actor, a.token)]); assert.equal(f.calls.length, 1); await assert.rejects(f.service.advance(f.guild, f.actor, b.token), /Week changed/); const replay = await createWeekAdvancementService(f.options).advance(f.guild, f.actor, a.token); assert.equal(replay.alreadyApplied, true); assert.equal(f.repository.loadLeague('l').league.currentWeek, 2); assert.equal(f.repository.loadAuditLog('l').filter(a => a.action === 'week.advanced').length, 1); });
test('thread failure leaves activation committed and retry can use existing creator', async t => { const f = fixture(t); await f.finals(); f.threads.create = async () => ({ created: 13, failed: 1 }); const result = await f.service.advance(f.guild, f.actor, f.service.prepare('g', f.actor).token); assert.equal(result.threads.failed, 1); assert.equal(f.repository.loadLeague('l').league.currentWeek, 2); f.threads.create = async () => ({ created: 1, existing: 13, failed: 0 }); assert.equal((await f.threads.create(f.guild)).created, 1); const other = fixture(t); await other.finals(); other.threads.create = async () => { throw Error('Discord unavailable'); }; const failed = await other.service.advance(other.guild, other.actor, other.service.prepare('g', other.actor).token); assert.equal(failed.threadError, 'Discord unavailable'); assert.equal(other.repository.loadLeague('l').league.currentWeek, 2); });
test('Week 15 completes regular season without Week 16, playoffs or altering results', async t => { const f = fixture(t); let schedule = f.repository.loadSchedule('l', '1'); for (const w of schedule.weeks) w.status = w.week === 15 ? 'ACTIVE' : 'COMPLETED'; f.repository.saveSchedule(schedule); f.repository.saveLeague('l', { ...f.repository.loadLeague('l').league, currentWeek: 15 }); await f.finals(15); const result = await f.service.advance(f.guild, f.actor, f.service.prepare('g', f.actor).token); assert.equal(result.seasonComplete, true); const league = f.repository.loadLeague('l').league; assert.equal(league.regularSeasonStatus, 'COMPLETED'); assert.equal(league.currentPhase, 'REGULAR_SEASON'); assert.equal(league.currentWeek, 15); schedule = f.repository.loadSchedule('l', '1'); assert.equal(schedule.weeks.length, 15); assert.ok(schedule.weeks.every(w => w.status === 'COMPLETED')); assert.equal(f.calls.length, 0); assert.equal(f.service.inspect('g').seasonComplete, true); });
test('failed journal commit leaves original state; interrupted committed write recovers on restart', async t => {
    const f = fixture(t); await f.finals(); const before = f.repository.loadSchedule('l', '1'), prep = f.service.prepare('g', f.actor), rename = fs.renameSync; fs.renameSync = (a, b) => { if (b.endsWith('week-transaction.json')) throw Error('Disk failure'); return rename(a, b); }; try { await assert.rejects(f.service.advance(f.guild, f.actor, prep.token), /Disk failure/); } finally { fs.renameSync = rename; } assert.deepEqual(f.repository.loadSchedule('l', '1'), before); assert.equal(f.repository.loadLeague('l').league.currentWeek, 1);
    let tripped = false; fs.renameSync = (a, b) => { if (!tripped && b.endsWith('current-schedule.json')) { tripped = true; throw Error('Interrupted'); } return rename(a, b); }; try { await assert.rejects(f.service.advance(f.guild, f.actor, prep.token), /Interrupted/); } finally { fs.renameSync = rename; }
    const restarted = createFantasyHQRepository({ dataRoot: f.repository.dataRoot }); assert.equal(restarted.loadLeague('l').league.currentWeek, 2); const after = restarted.loadSchedule('l', '1'); assert.equal(after.weeks.filter(w => w.status === 'ACTIVE').length, 1); assert.equal(after.weeks[1].deadlineAt, undefined); assert.equal(restarted.loadAuditLog('l').filter(a => a.action === 'week.advanced').length, 1);
});
test('confirmation is actor-bound and cancellable; Discord unauthorized users are blocked', async t => { const f = fixture(t); const p = f.service.prepare('g', f.actor, true); await assert.rejects(f.service.advance(f.guild, { authorized: true, id: 'other' }, p.token), /invalid/); f.service.cancel(p.token, f.actor); await assert.rejects(f.service.advance(f.guild, f.actor, p.token), /invalid/); await assert.rejects(require('../src/fantasyhq/discord-week').handleWeekCommand({ guildId: 'g', memberPermissions: { has: () => false }, member: { roles: [] } }, f.service), /Commish/); });
test('website week mutation API stays protected after its controls are removed', () => { const { requestHandler } = require('../src/web'); let status; requestHandler({ url: '/api/league/admin/week', method: 'POST', headers: {} }, { writeHead: c => status = c, end() { } }); assert.equal(status, 403); const html = fs.readFileSync('web/index.html', 'utf8'); for (const id of ['week-confirmation', 'week-force', 'game-cleanup-panel', 'game-thread-panel']) assert.doesNotMatch(html, new RegExp(`id="${id}"`)); });
test('website requires preparation and confirmation and returns unresolved investigation links', async t => {
    const f = fixture(t), { requestHandler, setGameThreadRuntime } = require('../src/web'), { Readable } = require('stream'); const old = process.env.WEBSITE_ADMIN_KEY; process.env.WEBSITE_ADMIN_KEY = 'week-test'; t.after(() => { setGameThreadRuntime(null); if (old === undefined) delete process.env.WEBSITE_ADMIN_KEY; else process.env.WEBSITE_ADMIN_KEY = old; }); setGameThreadRuntime({ client: { isReady: () => true, guilds: { fetch: async () => f.guild } }, weekService: f.service, repository: f.repository });
    function request(body) { return new Promise(resolve => { const req = Readable.from(body ? [JSON.stringify(body)] : []); Object.assign(req, { method: body ? 'POST' : 'GET', url: '/api/league/admin/week', headers: { 'x-leaguebuddy-admin-key': 'week-test' } }); let code; requestHandler(req, { writeHead: c => code = c, end: b => resolve({ code, data: JSON.parse(b) }) }); }); }
    assert.equal((await request()).data.unresolved.length, 14); assert.equal((await request({ action: 'confirm', operator: 'Test' })).code, 400); const prep = await request({ action: 'prepare', operator: 'Test', force: true }); assert.equal(prep.code, 200); assert.ok(prep.data.token); assert.equal(f.repository.loadLeague('l').league.currentWeek, 1); const result = await request({ action: 'confirm', operator: 'Test', token: prep.data.token }); assert.equal(result.data.currentWeek, 2); assert.equal(result.data.threads.created, 14); const audit = f.repository.loadAuditLog('l').find(e => e.action === 'week.advanced'); assert.equal(audit.operator, 'Test'); assert.equal(audit.commissionerUserId, 'commish');
});
test('Discord confirmation refreshes published league feeds only after a successful advance', async t => { const f = fixture(t); await f.finals(); const { handleWeekCommand, handleWeekButton } = require('../src/fantasyhq/discord-week'); let preview, reply, refreshes = 0; const base = { guildId: 'g', guild: f.guild, user: { id: 'commish' }, memberPermissions: { has: () => true }, options: { getBoolean: () => false }, editReply: async p => preview = p }; await handleWeekCommand(base, f.service); assert.equal(f.repository.loadLeague('l').league.currentWeek, 1); const customId = preview.components[0].toJSON().components[1].custom_id; await handleWeekButton({ ...base, customId, deferReply: async () => { }, editReply: async p => reply = p }, f.service, async result => { refreshes++; assert.equal(result.currentWeek, 2); }); assert.equal(reply.embeds[0].toJSON().title, 'WEEK 2 IS NOW ACTIVE'); assert.equal(f.calls.length, 1); assert.equal(refreshes, 1); });
test('expired confirmation cannot advance the league', async t => { const f = fixture(t); const p = f.service.prepare('g', f.actor, true); const later = createWeekAdvancementService({ ...f.options, now: () => f.options.now() + 6 * 60000 }); await assert.rejects(later.advance(f.guild, f.actor, p.token), /expired/); assert.equal(f.repository.loadLeague('l').league.currentWeek, 1); });
test('mock refresh request appears only after a finalized week transaction and replays remain idempotent', async t => {
    const f = fixture(t), file = path.join(f.repository.buildLeaguePaths(f.repository.dataRoot, 'l').leagueRoot, 'mock-draft', 'refresh.json');
    assert.equal(f.service.prepare('g', f.actor).blocked, true);
    assert.equal(fs.existsSync(file), false);
    await f.finals(); const prep = f.service.prepare('g', f.actor);
    assert.equal(fs.existsSync(file), false);
    await f.service.advance(f.guild, f.actor, prep.token);
    assert.equal(JSON.parse(fs.readFileSync(file, 'utf8')).events[0].id, `week:${prep.token}`);
    await createWeekAdvancementService(f.options).advance(f.guild, f.actor, prep.token);
    assert.equal(JSON.parse(fs.readFileSync(file, 'utf8')).events.length, 1);
});
test('public standings publish on advancement, stay frozen after late approvals, and include them at the next advancement', async t => {
    const f = fixture(t), standings = require('../src/fantasyhq/standings-service').createStandingsService({ submissions: f.submissions, publishedOnly: true });
    await f.finals(1, 12);
    assert.equal(standings.getStandings('l', '1').countedGames, 0);
    const prep = f.service.prepare('g', f.actor, true); await f.service.advance(f.guild, f.actor, prep.token);
    assert.equal(standings.getStandings('l', '1').countedGames, 12);
    const saved = f.repository.loadSchedule('l', '1'); assert.equal(saved.statsPublication.throughWeek, 1); assert.equal(saved.statsPublication.gameIds.length, 12);
    await f.finals(1, 14); await f.finals(2, 14);
    assert.equal(standings.getStandings('l', '1').countedGames, 12);
    assert.equal(f.service.inspect('g').final, 14); // Advancement checks approvals, independently of publication.
    const next = f.service.prepare('g', f.actor); await f.service.advance(f.guild, f.actor, next.token);
    assert.equal(standings.getStandings('l', '1').countedGames, 28);
    assert.equal(standings.getStandings('l', '1').publishedThroughWeek, 2);
});
