const PHASES = {
  SETUP: "SETUP",
  PRESEASON: "PRESEASON",
  REGULAR_SEASON: "REGULAR_SEASON",
  PLAYOFFS: "PLAYOFFS",
  OFFSEASON: "OFFSEASON",
  DRAFT: "DRAFT",
  FREE_AGENCY: "FREE_AGENCY",
};

const WEEK_STATUSES = Object.freeze({
  UPCOMING: "UPCOMING",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
});

module.exports = {
  WEEK_STATUSES,
  PHASES,
};
