const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, MessageFlags } = require('discord.js');
const { requireLeagueStaff } = require('./discord-permissions');
function actor(interaction) { requireLeagueStaff(interaction); return { authorized: true, id: interaction.user.id }; }
function confirmationPayload(view) {
    const embed = new EmbedBuilder().setColor(0xffdc21).setTitle(view.blocked ? `WEEK ${view.week} CANNOT BE COMPLETED` : view.nextWeek ? `COMPLETE WEEK ${view.week}?` : 'COMPLETE REGULAR SEASON?')
        .setDescription(`${view.final} / ${view.total} games final\n${view.unresolved.length} unresolved${view.unresolved.length ? '\n\n' + view.unresolved.map(g => `${g.team1Name} vs ${g.team2Name}`).join('\n') : ''}\n\n${view.blocked ? 'Resolve these games or explicitly request force advancement.' : view.force ? 'Force advancement preserves unresolved games without assigning results.' : view.nextWeek ? `Start Week ${view.nextWeek}, its 48-hour window, and its private game threads.` : 'Complete Week 15. Playoffs will not start.'}`);
    return { embeds: [embed], components: view.token ? [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('weekcancel:' + view.token).setLabel('Cancel').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('weekconfirm:' + view.token).setLabel(view.force ? 'Force Advance' : view.nextWeek ? 'Start Week ' + view.nextWeek : 'Complete Regular Season').setStyle(view.force ? ButtonStyle.Danger : ButtonStyle.Primary))] : [], allowedMentions: { parse: [] } };
}
function resultPayload(result) { return { embeds: [new EmbedBuilder().setColor(0xffdc21).setTitle(result.seasonComplete ? 'REGULAR SEASON COMPLETE' : `WEEK ${result.currentWeek} IS NOW ACTIVE`).setDescription(`Week ${result.previousWeek}: COMPLETED${result.seasonComplete ? '\nAll regular-season weeks closed.' : `\n${result.games} Games\n${result.deadlineAt ? `Deadline: <t:${Math.floor(Date.parse(result.deadlineAt) / 1000)}:F>` : "Countdown starts when game threads are created."}`}${result.threads ? `\n${result.threads.created} Threads Created\n${result.threads.existing} Existing\n${result.threads.failed} Failed` : ''}${result.threadError ? '\nThread creation needs retry: ' + result.threadError : ''}${result.alreadyApplied ? '\nThis advancement was already applied.' : ''}${result.forced ? '\nForced advancement: ' + result.unresolved.length + ' games remain unresolved.' : ''}`)], components: [], allowedMentions: { parse: [] } }; }
async function handleWeekCommand(interaction, service) { const a = actor(interaction); const view = service.prepare(interaction.guildId, a, interaction.options.getBoolean('force') === true); await interaction.editReply(confirmationPayload(view)); }
async function handleWeekButton(interaction, service, onAdvanced) { await interaction.deferReply({ flags: MessageFlags.Ephemeral }); try { const a = actor(interaction), [action, token] = interaction.customId.split(':'); if (action === 'weekcancel') { service.cancel(token, a); await interaction.editReply('Advancement cancelled.'); return; } const result = await service.advance(interaction.guild, a, token); await interaction.editReply(resultPayload(result)); if (onAdvanced) try { await onAdvanced(result); } catch (error) { console.error('League feed refresh after week advancement:', error.message); } } catch (error) { await interaction.editReply(error.message); } }
module.exports = { handleWeekCommand, handleWeekButton, confirmationPayload, resultPayload };
