const {EmbedBuilder}=require('discord.js');const {publishPermanentPost}=require('./discord-permanent-post');
const running=new Map();
function newsPayload(story,players,teams,mentions={users:[],roles:[]},notify=false){const player=players.find(p=>p.playerId===story.playerIds[0]),team=teams.find(t=>t.teamId===story.teamIds[0]),card=player?require('../shared/discord-player-card').nbaPlayerCard({...player,teamName:team?.teamName},'News'):null,embed=card?.embeds[0]||new EmbedBuilder().setColor(0xffdc21);embed.setTitle(story.headline).setDescription(story.article+(story.correctionNotice?'\n\n**Correction notice:** '+story.correctionNotice:''));embed.setFooter({text:'NEWS:'+story.id});embed.setTimestamp(new Date(story.publishedAt));return {content:[...mentions.users.map(id=>'<@'+id+'>'),...mentions.roles.map(id=>'<@&'+id+'>')].join(' '),embeds:[embed],files:card?.files||[],allowedMentions:{parse:[],users:notify?mentions.users:[],roles:notify?mentions.roles:[]}};}
function createDiscordNews({repository,submissions,now=Date.now}){
 const service=require('./news-service').createNewsService({repository,submissions,now});
 function reconcile(guild,leagueId){const key=repository.dataRoot+':'+leagueId;if(running.has(key))return running.get(key);const task=(async()=>{
  const settings=repository.loadSettings(leagueId);if(settings.simulationId)return;const stories=service.publishDue(leagueId);if(!stories.length)return;const channelId=settings.discordChannels?.news;if(!channelId)throw Error('Set up the News channel.');const channel=await guild.channels.fetch(channelId),players=repository.loadPlayers(leagueId),teams=repository.loadLeague(leagueId).teams;
  for(const story of stories){const mentions=story.publication?.mentions||{users:(story.breaking||['Trades','Free agency','Championships'].includes(story.category))?repository.loadOwners(leagueId).filter(o=>story.teamIds.includes(o.teamId)&&/^\d{17,20}$/.test(o.userId)).map(o=>o.userId):[],roles:story.category==='Championships'?[...(guild.roles?.cache?.values()||[])].filter(r=>r.name==='LEAGUEbuddy Coach').map(r=>r.id):[]};const version=require('crypto').createHash('sha256').update(JSON.stringify([story.headline,story.article,story.correctionNotice,story.featured])).digest('hex');if(story.publication?.messageId){const message=await channel.messages.fetch(story.publication.messageId);if(!message)throw Error('Published News message is missing; preserve its history before recreating.');if(story.publication.version!==version){await message.edit(newsPayload(story,players,teams,mentions));service.publication(leagueId,story.id,{...story.publication,version});}if(message.reactions?.cache)service.reactions(leagueId,story.id,Object.fromEntries([...message.reactions.cache.values()].map(reaction=>[reaction.emoji.id||reaction.emoji.name,Math.max(0,reaction.count-(reaction.me?1:0))])));continue;}
   await publishPermanentPost({key:key+':'+story.id,channel,marker:'NEWS:'+story.id,receipt:story.publication,now,payload:async()=>newsPayload(story,players,teams,mentions,true),save:p=>service.publication(leagueId,story.id,{...p,version,mentions})});
  }
 })().finally(()=>running.delete(key));running.set(key,task);return task;}
 return {service,reconcile};
}
module.exports={createDiscordNews,newsPayload};
