const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, MessageFlags, ModalBuilder, TextInputBuilder, TextInputStyle } = require('discord.js');
const { requireLeagueStaff } = require('./discord-permissions');
function actor(interaction) { requireLeagueStaff(interaction); return { authorized: true, id: interaction.user.id }; }
function confirmationPayload(view) {
    const embed = new EmbedBuilder().setColor(0xffdc21).setTitle(view.blocked ? `WEEK ${view.week} CANNOT BE COMPLETED` : view.nextWeek ? `COMPLETE WEEK ${view.week}?` : 'COMPLETE REGULAR SEASON?')
        .setDescription(`${view.final} / ${view.total} games final\n${view.unresolved.length} unresolved${view.unresolved.length ? '\n\n' + view.unresolved.map(g => `${g.threadUrl ? `[${g.team1Name} vs ${g.team2Name}](${g.threadUrl})` : `${g.team1Name} vs ${g.team2Name}`} · ${g.status?.replaceAll('_', ' ').toLowerCase() || 'unfinished'}${g.reviewPending ? ' · review needed' : g.extractionFailed ? ' · OCR retry needed' : ''}`).join('\n') : ''}\n\n${view.blocked ? 'Resolve these games or explicitly request force advancement.' : view.force ? 'Force advancement preserves unresolved games without assigning results.' : view.nextWeek ? `Start Week ${view.nextWeek}, its 48-hour window, and its private game threads.` : 'Complete Week 15, then use /week playoffs to review and confirm playoff seeding.'}`);
    return { embeds: [embed], components: view.token ? [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('weekcancel:' + view.token).setLabel('Cancel').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('weekconfirm:' + view.token).setLabel(view.force ? 'Force Advance' : view.nextWeek ? 'Start Week ' + view.nextWeek : 'Complete Regular Season').setStyle(view.force ? ButtonStyle.Danger : ButtonStyle.Primary))] : [], allowedMentions: { parse: [] } };
}
function resultPayload(result) { return { embeds: [new EmbedBuilder().setColor(0xffdc21).setTitle(result.seasonComplete ? 'REGULAR SEASON COMPLETE' : `WEEK ${result.currentWeek} IS NOW ACTIVE`).setDescription(`Week ${result.previousWeek}: COMPLETED${result.seasonComplete ? '\nAll regular-season weeks closed.' : `\n${result.games} Games\n${result.deadlineAt ? `Deadline: <t:${Math.floor(Date.parse(result.deadlineAt) / 1000)}:F>` : "Countdown starts when game threads are created."}`}${result.threads ? `\n${result.threads.created} Threads Created\n${result.threads.existing} Existing\n${result.threads.failed} Failed` : ''}${result.threadError ? '\nThread creation needs retry: ' + result.threadError : ''}${result.alreadyApplied ? '\nThis advancement was already applied.' : ''}${result.forced ? '\nForced advancement: ' + result.unresolved.length + ' games remain unresolved.' : ''}`)], components: result.seasonComplete ? [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('post:start').setLabel('Start Playoffs · Review Seeds').setStyle(ButtonStyle.Primary))] : [], allowedMentions: { parse: [] } }; }
async function handleWeekPreview(interaction, service, force = false) { const view = service.prepare(interaction.guildId, actor(interaction), force); await interaction.editReply(confirmationPayload(view)); }
async function handleWeekCommand(interaction, service) { requireLeagueStaff(interaction); if (interaction.options.getSubcommand?.() === 'playoffs') { const view = require('./season-transition').createSeasonTransitionService({ submissions: service.submissions }).prepare(interaction.guildId, actor(interaction)); await interaction.editReply(playoffPayload(view)); return; } return handleWeekPreview(interaction, service, interaction.options.getBoolean('force') === true); }
async function handleWeekButton(interaction, service, onAdvanced, postseason) {
  if (interaction.customId.startsWith('playoffedit:')) {
    actor(interaction); const token=interaction.customId.split(':')[1];
    await interaction.showModal(new ModalBuilder().setCustomId('playoffsave:'+token).setTitle('Adjust playoff seed').addComponents(
      ...[['conference','Conference: East or West'],['seed','Seed number: 1–10'],['team','Team name, abbreviation or ID']].map(([id,label])=>new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(TextInputStyle.Short).setRequired(true)))));return;
  }
  if (interaction.customId.startsWith('playoffsave:')) {
    await interaction.deferReply({flags:64});try {
      const a=actor(interaction),token=interaction.customId.split(':')[1],c=service.submissions.repository.loadLeagueContext({guildId:interaction.guildId}),query=interaction.fields.getTextInputValue('team').trim().toLowerCase();
      const team=c.teams.find(t=>[t.teamName,t.teamId,t.abbreviation].some(v=>v.toLowerCase()===query));
      const conference=interaction.fields.getTextInputValue('conference').trim().toLowerCase();
      const view=require('./season-transition').createSeasonTransitionService({submissions:service.submissions}).adjustSeed(interaction.guildId,a,token,conference==='east'?'East':conference==='west'?'West':conference,Number(interaction.fields.getTextInputValue('seed')),team?.teamId);
      await interaction.editReply(playoffPayload(view));
    }catch(error){await interaction.editReply(error.message);}return;
  }
  await interaction.deferReply({ flags: MessageFlags.Ephemeral }); try { const a = actor(interaction), [action, token] = interaction.customId.split(':'); if (action === 'playoffcancel') { require('./season-transition').createSeasonTransitionService({ submissions: service.submissions }).cancel(token,a); await interaction.editReply('Playoff handoff cancelled.'); return; } if (action === 'playoffconfirm') { const playoffs = require('./season-transition').createSeasonTransitionService({ submissions: service.submissions }).confirm(interaction.guildId, a, token); if(postseason)await postseason.createThreads(interaction.guild); await interaction.editReply(playoffPayload({ alreadyStarted: true, playoffs })); return; } if (action === 'weekcancel') { service.cancel(token, a); await interaction.editReply('Advancement cancelled.'); return; } const result = await service.advance(interaction.guild, a, token); await interaction.editReply(resultPayload(result)); if (onAdvanced) try { await onAdvanced(result); } catch (error) { console.error('League feed refresh after week advancement:', error.message); } } catch (error) { await interaction.editReply(error.message); } }
function playoffPayload(view) {
  const seeds = view.seeds || view.playoffs?.seeds || {};
  const text = Object.entries(seeds).map(([conference,teams]) => `**${conference}**\n${teams.map((t,i) => `${i+1}. ${t.teamName} · ${t.W}–${t.L}`).join('\n')}`).join('\n\n');
  const previews = Object.entries(seeds).map(([c,t]) => `${c}: ${t[6]?.teamName} vs ${t[7]?.teamName}; ${t[8]?.teamName} vs ${t[9]?.teamName}`).join('\n');
  const policy = 'Existing trades, FA windows and pending waivers keep their saved rules. Pending upgrades expire; new workflows close.';
  return { embeds: [new EmbedBuilder().setColor(0xffdc21).setTitle(view.alreadyStarted ? 'PLAYOFFS STARTED' : view.blocked ? 'PLAYOFFS BLOCKED' : view.legacyMigration ? 'CONFIRM PLAY-IN MIGRATION' : 'REVIEW PLAYOFF SEEDING').setDescription(`${text}\n\n**Play-In preview**\n${previews}\n\n${view.blocked ? `${view.unresolved.length} unresolved games must be finalized first.` : policy}`)], components: view.token ? [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('playoffedit:'+view.token).setLabel('Adjust Seeds').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('playoffcancel:'+view.token).setLabel('Cancel').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId('playoffconfirm:'+view.token).setLabel('Confirm playoffs').setStyle(ButtonStyle.Success))] : [], allowedMentions: { parse: [] } };
}
module.exports = { playoffPayload, handleWeekPreview, handleWeekCommand, handleWeekButton, confirmationPayload, resultPayload };
