const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');const {publishPermanentPost}=require('./discord-permanent-post');
const jobs=new Map();
function streamPayload(game,facts){const record=teamId=>{const row=facts.teams.find(t=>t.teamId===teamId);return row?row.wins+'-'+row.losses:'—';},label=require('../shared/team-emojis').teamLabel,embed=new EmbedBuilder().setTitle('📺 '+game.team1Name+' vs '+game.team2Name).setColor(0xffdc21).setDescription(`📅 Week ${game.weekNumber}${game.inGameDate?' · '+game.inGameDate:''}\n${label(game.team1Name)} **${record(game.team1Id)}** vs ${label(game.team2Name)} **${record(game.team2Id)}**\n\n**🔥 Players to watch**\n${facts.playersToWatch.map(p=>`**${p.name}** · ${p.PPG.toFixed(1)} PTS / ${p.RPG.toFixed(1)} REB / ${p.APG.toFixed(1)} AST`).join('\n')||'No published player statistics yet.'}\n\n**📊 Game breakdown**\n${facts.breakdown}\n\n**🔮 Predicted winner**\n${facts.prediction?facts.prediction.teamName+' · '+facts.prediction.reason:'No verified prediction available.'}\n\n📺 [Watch live](${game.streamlink.url})`).setFooter({text:'STREAM:'+game.gameId}),buttons=[new ButtonBuilder().setLabel('Watch live').setURL(game.streamlink.url).setStyle(ButtonStyle.Link)];try{const base=process.env.WEBSITE_URL||(process.env.RAILWAY_PUBLIC_DOMAIN?'https://'+process.env.RAILWAY_PUBLIC_DOMAIN:''),url=new URL('/',base);url.searchParams.set('gameId',game.gameId);url.hash='streams';if(['https:','http:'].includes(url.protocol)){buttons.push(new ButtonBuilder().setLabel('Game page').setURL(url.href).setStyle(ButtonStyle.Link));}}catch{}buttons.push(new ButtonBuilder().setLabel('Sportsbook').setCustomId('book:open').setStyle(ButtonStyle.Secondary));return {embeds:[embed],components:[new ActionRowBuilder().addComponents(...buttons)],allowedMentions:{parse:[]}};}
function createDiscordStreams({repository,submissions,now=Date.now}){
 function publish(guild,gameId){const key=repository.dataRoot+':'+gameId;if(jobs.has(key))return jobs.get(key);const task=(async()=>{let record=submissions.load(gameId),game=record.game,settings=repository.loadSettings(game.leagueId);if(settings.simulationId||game.simulationId||!game.streamlink?.url)return;if(!settings.discordChannels?.streamlink)throw Error('Set up the Streamlink channel.');const channel=await guild.channels.fetch(settings.discordChannels.streamlink);
  if(!game.streamAnnouncement?.facts){const facts=require('./streams-service').createStreamsService({repository,submissions}).facts(game);await submissions.mutate(gameId,r=>{r.game.streamAnnouncement ||= {};r.game.streamAnnouncement.facts ||= facts;});game=submissions.load(gameId).game;}
  const facts=game.streamAnnouncement.facts,version=game.streamlink.url;
  if(game.streamAnnouncement.publication?.messageId){if(game.streamAnnouncement.publication.version===version)return;const message=await channel.messages.fetch(game.streamAnnouncement.publication.messageId);if(!message)throw Error('The original Streamlink announcement is missing; Staff must reconcile it before reposting.');await message.edit(streamPayload(game,facts));await submissions.mutate(gameId,r=>{r.game.streamAnnouncement.publication.version=version;});return;}
  await publishPermanentPost({key:key+':post',channel,marker:'STREAM:'+gameId,receipt:game.streamAnnouncement.publication,now,payload:async()=>streamPayload(game,facts),save:async p=>{await submissions.mutate(gameId,r=>{r.game.streamAnnouncement ||= {facts};r.game.streamAnnouncement.publication={...p,version};});}});
 })().finally(()=>jobs.delete(key));jobs.set(key,task);return task;}
 async function reconcile(guild,leagueId){for(const r of submissions.records().filter(r=>r.game.leagueId===leagueId&&r.game.streamlink?.url))await publish(guild,r.game.gameId);}
 return {publish,reconcile};
}
module.exports={createDiscordStreams,streamPayload};
