const fs=require('fs'),path=require('path'),{randomUUID,createHash}=require('crypto');
const {createFantasyHQRepository}=require('./repository');
const processToken=randomUUID();
function atomic(file,value){require('./storage-safety').assertWriterLease(file);fs.mkdirSync(path.dirname(file),{recursive:true});const temp=file+'.'+randomUUID()+'.tmp';try{const fd=fs.openSync(temp,'wx');try{fs.writeFileSync(fd,JSON.stringify(value,null,2));fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(temp,file);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
function read(file){return JSON.parse(fs.readFileSync(file,'utf8'));}
function copy(source,target){if(!fs.existsSync(source))return;const stat=fs.lstatSync(source);if(stat.isSymbolicLink())throw Error('Snapshot contains a symbolic link; copy refused.');if(stat.isDirectory()){fs.mkdirSync(target,{recursive:true});for(const name of fs.readdirSync(source)){if(name.endsWith('.tmp')||['.writer-lock','.writer-recovery','backups'].includes(name))continue;copy(path.join(source,name),path.join(target,name));}}else{fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(source,target);}}
function inventory(root,relative=''){const rows=[];for(const name of fs.readdirSync(path.join(root,relative))){const next=path.join(relative,name),file=path.join(root,next);if(fs.lstatSync(file).isSymbolicLink())throw Error('Checkpoint symlink refused.');if(fs.statSync(file).isDirectory())rows.push(...inventory(root,next));else rows.push({name:next,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')});}return rows;}
function verifyInventory(root,files){if(!Array.isArray(files)||!files.length)throw Error('Checkpoint has no completeness manifest.');for(const entry of files){if(!entry.name||path.isAbsolute(entry.name)||entry.name.split(/[\\/]/).some(n=>!n||n==='.'||n==='..'))throw Error('Unsafe checkpoint path.');const file=path.join(root,entry.name);if(!fs.existsSync(file)||createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==entry.sha256)throw Error('Checkpoint is incomplete or corrupted.');}if(inventory(root).length!==files.length)throw Error('Checkpoint file manifest does not match its contents.');}
function validateWorkspace(root,leagueId){const repository=createFantasyHQRepository({dataRoot:root}),context=repository.loadLeague(leagueId),players=repository.loadPlayers(leagueId),ids=new Set();for(const p of players){if(!p.playerId||ids.has(p.playerId))throw Error('Snapshot player IDs are missing or duplicated.');ids.add(p.playerId);}for(const m of repository.loadRosterMemberships(leagueId))if(!ids.has(m.playerId))throw Error('Snapshot membership references an unknown player.');repository.loadDraftPicks(leagueId);repository.loadSettings(leagueId);repository.loadAuditLog(leagueId);if(repository.scheduleExists(leagueId,context.seasonId))repository.loadSchedule(leagueId,context.seasonId);return repository;}
function createSimulationStorage({repository,now=Date.now}){
  const root=path.join(repository.dataRoot,'simulations');
  function authorize(leagueId,actor){require('./postseason-state').requireCommissioner(repository.loadLeague(leagueId),actor);}
  function directory(id){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('Invalid simulation identity.');return path.join(root,id);}
  function recover(id){const dir=directory(id),journal=path.join(dir,'restore.json');if(!fs.existsSync(journal))return;const tx=read(journal);if(!/^[a-f0-9-]{36}$/.test(tx.backupId))throw Error('Invalid restore journal.');const workspace=path.join(dir,'workspace'),candidate=path.join(dir,'restore-candidate'),backup=path.join(dir,'safety',tx.backupId);if(fs.existsSync(candidate)){if(fs.existsSync(workspace)){fs.mkdirSync(path.dirname(backup),{recursive:true});fs.renameSync(workspace,backup);}fs.renameSync(candidate,workspace);}if(!fs.existsSync(workspace))throw Error('Interrupted simulation restoration requires recovery from safety backup.');validateWorkspace(workspace,tx.leagueId);const runtimeFile=path.join(workspace,'simulation-runtime.json');if(fs.existsSync(runtimeFile)){const runtime=read(runtimeFile);runtime.status='IDLE';runtime.pauseRequested=false;atomic(runtimeFile,runtime);}fs.unlinkSync(journal);}
  function load(id,actor){recover(id);const dir=directory(id),meta=read(path.join(dir,'identity.json'));authorize(meta.leagueId,actor);const runtimeFile=path.join(dir,'workspace','simulation-runtime.json');if(fs.existsSync(runtimeFile)){const runtime=read(runtimeFile);if(runtime.status==='RUNNING'&&runtime.processToken!==processToken){runtime.status=runtime.plan?'PAUSED':'IDLE';runtime.errors.push({error:'Previous simulation process stopped; saved games were preserved.'});atomic(runtimeFile,runtime);}}return {...meta,dir,workspace:path.join(dir,'workspace'),repository:validateWorkspace(path.join(dir,'workspace'),meta.leagueId)};}
  function create(leagueId,actor){authorize(leagueId,actor);const id=randomUUID(),dir=directory(id),workspace=path.join(dir,'workspace'),context=repository.loadLeague(leagueId);copy(context.paths.leagueRoot,path.join(workspace,'leagues',leagueId));const live=require('./game-submissions').createGameSubmissionService({repository});for(const r of live.records().filter(r=>r.game.leagueId===leagueId))copy(path.join(repository.dataRoot,'game-history',r.game.gameId),path.join(workspace,'game-history',r.game.gameId));const isolated=validateWorkspace(workspace,leagueId);isolated.saveGuildLeagueBinding(context.league.guildId||'simulation',{leagueId,seasonId:context.seasonId});isolated.saveSettings(leagueId,{...isolated.loadSettings(leagueId),testMode:true,simulationId:id});atomic(path.join(dir,'identity.json'),{version:1,id,leagueId,seasonId:context.seasonId,createdBy:actor.id,createdAt:new Date(now()).toISOString()});atomic(path.join(workspace,'simulation-runtime.json'),{version:1,simulationId:id,transactions:[],development:{},history:[],discordContent:[],errors:[]});checkpoint(id,actor,'Starting state',true);return load(id,actor);}
  function checkpoints(id,actor){const sim=load(id,actor),dir=path.join(sim.dir,'checkpoints');return fs.readdirSync(dir).filter(n=>/^[a-f0-9-]{36}$/.test(n)).map(n=>read(path.join(dir,n,'manifest.json')));}
  function checkpoint(id,actor,name,automatic=false){const sim=load(id,actor),checkpointId=randomUUID(),target=path.join(sim.dir,'checkpoints',checkpointId);if(!String(name||'').trim()||String(name).length>100)throw Error('Checkpoint name must contain 1–100 characters.');const payload=path.join(target,'data');copy(sim.workspace,payload);validateWorkspace(payload,sim.leagueId);const manifest={version:1,id:checkpointId,simulationId:id,name,automatic,createdBy:actor.id,createdAt:new Date(now()).toISOString(),phase:sim.repository.loadLeague(sim.leagueId).league.currentPhase,files:inventory(payload)};atomic(path.join(target,'manifest.json'),manifest);return manifest;}
  function restore(id,actor,checkpointId,confirmed=false){const sim=load(id,actor);if(read(path.join(sim.workspace,'simulation-runtime.json')).status==='RUNNING')throw Error('Stop the active simulation before restoring.');if(!confirmed)throw Error('Explicit checkpoint restoration confirmation required.');if(!/^[a-f0-9-]{36}$/.test(checkpointId))throw Error('Invalid checkpoint ID.');const target=path.join(sim.dir,'checkpoints',checkpointId),manifest=read(path.join(target,'manifest.json'));if(manifest.simulationId!==id)throw Error('Checkpoint belongs to another simulation.');verifyInventory(path.join(target,'data'),manifest.files);const candidate=path.join(sim.dir,'restore-candidate');if(fs.existsSync(candidate))throw Error('A restoration is already pending.');copy(path.join(target,'data'),candidate);validateWorkspace(candidate,sim.leagueId);atomic(path.join(sim.dir,'restore.json'),{leagueId:sim.leagueId,checkpointId,backupId:randomUUID()});recover(id);return load(id,actor);}
  function runtime(id,actor){return read(path.join(load(id,actor).workspace,'simulation-runtime.json'));}
  function saveRuntime(id,actor,value){if(value.simulationId!==id)throw Error('Simulation identity mismatch.');if(value.status==='RUNNING')value.processToken=processToken;atomic(path.join(load(id,actor).workspace,'simulation-runtime.json'),value);return value;}
  return {create,load,checkpoints,checkpoint,restore,runtime,saveRuntime};
}
module.exports={createSimulationStorage,atomic,copy,validateWorkspace};
